//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01", IsNullable=false)]
public partial class Document {
    
    private ATMDiagnosticResponseV01 aTMDgnstcRspnField;
    
    /// <remarks/>
    public ATMDiagnosticResponseV01 ATMDgnstcRspn {
        get {
            return this.aTMDgnstcRspnField;
        }
        set {
            this.aTMDgnstcRspnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ATMDiagnosticResponseV01 {
    
    private Header20 hdrField;
    
    private ContentInformationType10 prtctdATMDgnstcRspnField;
    
    private ATMDiagnosticResponse1 aTMDgnstcRspnField;
    
    private ContentInformationType15 sctyTrlrField;
    
    /// <remarks/>
    public Header20 Hdr {
        get {
            return this.hdrField;
        }
        set {
            this.hdrField = value;
        }
    }
    
    /// <remarks/>
    public ContentInformationType10 PrtctdATMDgnstcRspn {
        get {
            return this.prtctdATMDgnstcRspnField;
        }
        set {
            this.prtctdATMDgnstcRspnField = value;
        }
    }
    
    /// <remarks/>
    public ATMDiagnosticResponse1 ATMDgnstcRspn {
        get {
            return this.aTMDgnstcRspnField;
        }
        set {
            this.aTMDgnstcRspnField = value;
        }
    }
    
    /// <remarks/>
    public ContentInformationType15 SctyTrlr {
        get {
            return this.sctyTrlrField;
        }
        set {
            this.sctyTrlrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class Header20 {
    
    private ATMMessageFunction1 msgFctnField;
    
    private string prtcolVrsnField;
    
    private string xchgIdField;
    
    private System.DateTime creDtTmField;
    
    private string initgPtyField;
    
    private string rcptPtyField;
    
    private string prcStatField;
    
    private Traceability4[] tracbltField;
    
    /// <remarks/>
    public ATMMessageFunction1 MsgFctn {
        get {
            return this.msgFctnField;
        }
        set {
            this.msgFctnField = value;
        }
    }
    
    /// <remarks/>
    public string PrtcolVrsn {
        get {
            return this.prtcolVrsnField;
        }
        set {
            this.prtcolVrsnField = value;
        }
    }
    
    /// <remarks/>
    public string XchgId {
        get {
            return this.xchgIdField;
        }
        set {
            this.xchgIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
    
    /// <remarks/>
    public string InitgPty {
        get {
            return this.initgPtyField;
        }
        set {
            this.initgPtyField = value;
        }
    }
    
    /// <remarks/>
    public string RcptPty {
        get {
            return this.rcptPtyField;
        }
        set {
            this.rcptPtyField = value;
        }
    }
    
    /// <remarks/>
    public string PrcStat {
        get {
            return this.prcStatField;
        }
        set {
            this.prcStatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tracblt")]
    public Traceability4[] Tracblt {
        get {
            return this.tracbltField;
        }
        set {
            this.tracbltField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ATMMessageFunction1 {
    
    private MessageFunction7Code fctnField;
    
    private string aTMSvcCdField;
    
    private string hstSvcCdField;
    
    /// <remarks/>
    public MessageFunction7Code Fctn {
        get {
            return this.fctnField;
        }
        set {
            this.fctnField = value;
        }
    }
    
    /// <remarks/>
    public string ATMSvcCd {
        get {
            return this.aTMSvcCdField;
        }
        set {
            this.aTMSvcCdField = value;
        }
    }
    
    /// <remarks/>
    public string HstSvcCd {
        get {
            return this.hstSvcCdField;
        }
        set {
            this.hstSvcCdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum MessageFunction7Code {
    
    /// <remarks/>
    BALN,
    
    /// <remarks/>
    CMPA,
    
    /// <remarks/>
    CMPD,
    
    /// <remarks/>
    ACMD,
    
    /// <remarks/>
    DVCC,
    
    /// <remarks/>
    DIAQ,
    
    /// <remarks/>
    DIAP,
    
    /// <remarks/>
    GSTS,
    
    /// <remarks/>
    INQQ,
    
    /// <remarks/>
    INQP,
    
    /// <remarks/>
    KYAQ,
    
    /// <remarks/>
    KYAP,
    
    /// <remarks/>
    PINQ,
    
    /// <remarks/>
    PINP,
    
    /// <remarks/>
    RJAQ,
    
    /// <remarks/>
    RJAP,
    
    /// <remarks/>
    WITV,
    
    /// <remarks/>
    WITK,
    
    /// <remarks/>
    WITQ,
    
    /// <remarks/>
    WITP,
    
    /// <remarks/>
    INQC,
    
    /// <remarks/>
    H2AP,
    
    /// <remarks/>
    H2AQ,
    
    /// <remarks/>
    TMOP,
    
    /// <remarks/>
    CSEC,
    
    /// <remarks/>
    DSEC,
    
    /// <remarks/>
    SKSC,
    
    /// <remarks/>
    SSTS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class EncapsulatedContent3 {
    
    private ContentType2Code cnttTpField;
    
    private byte[] cnttField;
    
    /// <remarks/>
    public ContentType2Code CnttTp {
        get {
            return this.cnttTpField;
        }
        set {
            this.cnttTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Cntt {
        get {
            return this.cnttField;
        }
        set {
            this.cnttField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum ContentType2Code {
    
    /// <remarks/>
    DATA,
    
    /// <remarks/>
    SIGN,
    
    /// <remarks/>
    EVLP,
    
    /// <remarks/>
    DGST,
    
    /// <remarks/>
    AUTH,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class Parameter7 {
    
    private byte[] initlstnVctrField;
    
    private BytePadding1Code bPddgField;
    
    private bool bPddgFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] InitlstnVctr {
        get {
            return this.initlstnVctrField;
        }
        set {
            this.initlstnVctrField = value;
        }
    }
    
    /// <remarks/>
    public BytePadding1Code BPddg {
        get {
            return this.bPddgField;
        }
        set {
            this.bPddgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BPddgSpecified {
        get {
            return this.bPddgFieldSpecified;
        }
        set {
            this.bPddgFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum BytePadding1Code {
    
    /// <remarks/>
    LNGT,
    
    /// <remarks/>
    NUL8,
    
    /// <remarks/>
    NULG,
    
    /// <remarks/>
    NULL,
    
    /// <remarks/>
    RAND,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class AlgorithmIdentification15 {
    
    private Algorithm12Code algoField;
    
    private Parameter7 paramField;
    
    /// <remarks/>
    public Algorithm12Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter7 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum Algorithm12Code {
    
    /// <remarks/>
    MACC,
    
    /// <remarks/>
    MCCS,
    
    /// <remarks/>
    CMA1,
    
    /// <remarks/>
    MCC1,
    
    /// <remarks/>
    CMA9,
    
    /// <remarks/>
    CMA5,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class AuthenticatedData4 {
    
    private decimal vrsnField;
    
    private bool vrsnFieldSpecified;
    
    private Recipient4Choice[] rcptField;
    
    private AlgorithmIdentification15 mACAlgoField;
    
    private EncapsulatedContent3 ncpsltdCnttField;
    
    private byte[] mACField;
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrsnSpecified {
        get {
            return this.vrsnFieldSpecified;
        }
        set {
            this.vrsnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rcpt")]
    public Recipient4Choice[] Rcpt {
        get {
            return this.rcptField;
        }
        set {
            this.rcptField = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification15 MACAlgo {
        get {
            return this.mACAlgoField;
        }
        set {
            this.mACAlgoField = value;
        }
    }
    
    /// <remarks/>
    public EncapsulatedContent3 NcpsltdCntt {
        get {
            return this.ncpsltdCnttField;
        }
        set {
            this.ncpsltdCnttField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] MAC {
        get {
            return this.mACField;
        }
        set {
            this.mACField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class Recipient4Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KEK", typeof(KEK4))]
    [System.Xml.Serialization.XmlElementAttribute("KeyIdr", typeof(KEKIdentifier2))]
    [System.Xml.Serialization.XmlElementAttribute("KeyTrnsprt", typeof(KeyTransport4))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class KEK4 {
    
    private decimal vrsnField;
    
    private bool vrsnFieldSpecified;
    
    private KEKIdentifier2 kEKIdField;
    
    private AlgorithmIdentification13 keyNcrptnAlgoField;
    
    private byte[] ncrptdKeyField;
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrsnSpecified {
        get {
            return this.vrsnFieldSpecified;
        }
        set {
            this.vrsnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public KEKIdentifier2 KEKId {
        get {
            return this.kEKIdField;
        }
        set {
            this.kEKIdField = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification13 KeyNcrptnAlgo {
        get {
            return this.keyNcrptnAlgoField;
        }
        set {
            this.keyNcrptnAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] NcrptdKey {
        get {
            return this.ncrptdKeyField;
        }
        set {
            this.ncrptdKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class KEKIdentifier2 {
    
    private string keyIdField;
    
    private string keyVrsnField;
    
    private decimal seqNbField;
    
    private bool seqNbFieldSpecified;
    
    private byte[] derivtnIdField;
    
    /// <remarks/>
    public string KeyId {
        get {
            return this.keyIdField;
        }
        set {
            this.keyIdField = value;
        }
    }
    
    /// <remarks/>
    public string KeyVrsn {
        get {
            return this.keyVrsnField;
        }
        set {
            this.keyVrsnField = value;
        }
    }
    
    /// <remarks/>
    public decimal SeqNb {
        get {
            return this.seqNbField;
        }
        set {
            this.seqNbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SeqNbSpecified {
        get {
            return this.seqNbFieldSpecified;
        }
        set {
            this.seqNbFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] DerivtnId {
        get {
            return this.derivtnIdField;
        }
        set {
            this.derivtnIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class AlgorithmIdentification13 {
    
    private Algorithm13Code algoField;
    
    private Parameter6 paramField;
    
    /// <remarks/>
    public Algorithm13Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter6 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum Algorithm13Code {
    
    /// <remarks/>
    EA2C,
    
    /// <remarks/>
    E3DC,
    
    /// <remarks/>
    DKP9,
    
    /// <remarks/>
    UKPT,
    
    /// <remarks/>
    UKA1,
    
    /// <remarks/>
    EA9C,
    
    /// <remarks/>
    EA5C,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class Parameter6 {
    
    private EncryptionFormat1Code ncrptnFrmtField;
    
    private bool ncrptnFrmtFieldSpecified;
    
    private byte[] initlstnVctrField;
    
    private BytePadding1Code bPddgField;
    
    private bool bPddgFieldSpecified;
    
    /// <remarks/>
    public EncryptionFormat1Code NcrptnFrmt {
        get {
            return this.ncrptnFrmtField;
        }
        set {
            this.ncrptnFrmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NcrptnFrmtSpecified {
        get {
            return this.ncrptnFrmtFieldSpecified;
        }
        set {
            this.ncrptnFrmtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] InitlstnVctr {
        get {
            return this.initlstnVctrField;
        }
        set {
            this.initlstnVctrField = value;
        }
    }
    
    /// <remarks/>
    public BytePadding1Code BPddg {
        get {
            return this.bPddgField;
        }
        set {
            this.bPddgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BPddgSpecified {
        get {
            return this.bPddgFieldSpecified;
        }
        set {
            this.bPddgFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum EncryptionFormat1Code {
    
    /// <remarks/>
    TR31,
    
    /// <remarks/>
    TR34,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class KeyTransport4 {
    
    private decimal vrsnField;
    
    private bool vrsnFieldSpecified;
    
    private Recipient5Choice rcptIdField;
    
    private AlgorithmIdentification11 keyNcrptnAlgoField;
    
    private byte[] ncrptdKeyField;
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrsnSpecified {
        get {
            return this.vrsnFieldSpecified;
        }
        set {
            this.vrsnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Recipient5Choice RcptId {
        get {
            return this.rcptIdField;
        }
        set {
            this.rcptIdField = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification11 KeyNcrptnAlgo {
        get {
            return this.keyNcrptnAlgoField;
        }
        set {
            this.keyNcrptnAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] NcrptdKey {
        get {
            return this.ncrptdKeyField;
        }
        set {
            this.ncrptdKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class Recipient5Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IssrAndSrlNb", typeof(IssuerAndSerialNumber1))]
    [System.Xml.Serialization.XmlElementAttribute("KeyIdr", typeof(KEKIdentifier2))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class IssuerAndSerialNumber1 {
    
    private RelativeDistinguishedName1[] issrField;
    
    private byte[] srlNbField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("RltvDstngshdNm", IsNullable=false)]
    public RelativeDistinguishedName1[] Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] SrlNb {
        get {
            return this.srlNbField;
        }
        set {
            this.srlNbField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class RelativeDistinguishedName1 {
    
    private AttributeType1Code attrTpField;
    
    private string attrValField;
    
    /// <remarks/>
    public AttributeType1Code AttrTp {
        get {
            return this.attrTpField;
        }
        set {
            this.attrTpField = value;
        }
    }
    
    /// <remarks/>
    public string AttrVal {
        get {
            return this.attrValField;
        }
        set {
            this.attrValField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum AttributeType1Code {
    
    /// <remarks/>
    CNAT,
    
    /// <remarks/>
    LATT,
    
    /// <remarks/>
    OATT,
    
    /// <remarks/>
    OUAT,
    
    /// <remarks/>
    CATT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class AlgorithmIdentification11 {
    
    private Algorithm7Code algoField;
    
    private Parameter4 paramField;
    
    /// <remarks/>
    public Algorithm7Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter4 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum Algorithm7Code {
    
    /// <remarks/>
    ERSA,
    
    /// <remarks/>
    RSAO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class Parameter4 {
    
    private EncryptionFormat1Code ncrptnFrmtField;
    
    private bool ncrptnFrmtFieldSpecified;
    
    private Algorithm11Code dgstAlgoField;
    
    private bool dgstAlgoFieldSpecified;
    
    private AlgorithmIdentification12 mskGnrtrAlgoField;
    
    /// <remarks/>
    public EncryptionFormat1Code NcrptnFrmt {
        get {
            return this.ncrptnFrmtField;
        }
        set {
            this.ncrptnFrmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NcrptnFrmtSpecified {
        get {
            return this.ncrptnFrmtFieldSpecified;
        }
        set {
            this.ncrptnFrmtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Algorithm11Code DgstAlgo {
        get {
            return this.dgstAlgoField;
        }
        set {
            this.dgstAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DgstAlgoSpecified {
        get {
            return this.dgstAlgoFieldSpecified;
        }
        set {
            this.dgstAlgoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification12 MskGnrtrAlgo {
        get {
            return this.mskGnrtrAlgoField;
        }
        set {
            this.mskGnrtrAlgoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum Algorithm11Code {
    
    /// <remarks/>
    HS25,
    
    /// <remarks/>
    HS38,
    
    /// <remarks/>
    HS51,
    
    /// <remarks/>
    HS01,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class AlgorithmIdentification12 {
    
    private Algorithm8Code algoField;
    
    private Parameter5 paramField;
    
    /// <remarks/>
    public Algorithm8Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter5 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum Algorithm8Code {
    
    /// <remarks/>
    MGF1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class Parameter5 {
    
    private Algorithm11Code dgstAlgoField;
    
    private bool dgstAlgoFieldSpecified;
    
    /// <remarks/>
    public Algorithm11Code DgstAlgo {
        get {
            return this.dgstAlgoField;
        }
        set {
            this.dgstAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DgstAlgoSpecified {
        get {
            return this.dgstAlgoFieldSpecified;
        }
        set {
            this.dgstAlgoFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ContentInformationType15 {
    
    private ContentType2Code cnttTpField;
    
    private AuthenticatedData4 authntcdDataField;
    
    /// <remarks/>
    public ContentType2Code CnttTp {
        get {
            return this.cnttTpField;
        }
        set {
            this.cnttTpField = value;
        }
    }
    
    /// <remarks/>
    public AuthenticatedData4 AuthntcdData {
        get {
            return this.authntcdDataField;
        }
        set {
            this.authntcdDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ATMCommandParameters1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ATMReqrdGblSts", typeof(ATMStatus1Code))]
    [System.Xml.Serialization.XmlElementAttribute("ReqrdCfgtnParam", typeof(ATMConfigurationParameter1))]
    [System.Xml.Serialization.XmlElementAttribute("XpctdMsgFctn", typeof(MessageFunction8Code))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum ATMStatus1Code {
    
    /// <remarks/>
    INSV,
    
    /// <remarks/>
    OUTS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ATMConfigurationParameter1 {
    
    private DataSetCategory7Code tpField;
    
    private string vrsnField;
    
    /// <remarks/>
    public DataSetCategory7Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum DataSetCategory7Code {
    
    /// <remarks/>
    ATMC,
    
    /// <remarks/>
    ATMP,
    
    /// <remarks/>
    APPR,
    
    /// <remarks/>
    CRAP,
    
    /// <remarks/>
    CPRC,
    
    /// <remarks/>
    OEXR,
    
    /// <remarks/>
    AMNT,
    
    /// <remarks/>
    LOCC,
    
    /// <remarks/>
    MNOC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum MessageFunction8Code {
    
    /// <remarks/>
    BALN,
    
    /// <remarks/>
    GSTS,
    
    /// <remarks/>
    DSEC,
    
    /// <remarks/>
    INQC,
    
    /// <remarks/>
    KEYQ,
    
    /// <remarks/>
    SSTS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ATMCommandIdentification1 {
    
    private string orgnField;
    
    private string refField;
    
    private string prcrField;
    
    /// <remarks/>
    public string Orgn {
        get {
            return this.orgnField;
        }
        set {
            this.orgnField = value;
        }
    }
    
    /// <remarks/>
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    public string Prcr {
        get {
            return this.prcrField;
        }
        set {
            this.prcrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ATMCommand1 {
    
    private ATMCommand1Code tpField;
    
    private TMSContactLevel2Code urgcyField;
    
    private System.DateTime dtTmField;
    
    private bool dtTmFieldSpecified;
    
    private ATMCommandIdentification1 cmdIdField;
    
    private ATMCommandParameters1Choice cmdParamsField;
    
    /// <remarks/>
    public ATMCommand1Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public TMSContactLevel2Code Urgcy {
        get {
            return this.urgcyField;
        }
        set {
            this.urgcyField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DtTm {
        get {
            return this.dtTmField;
        }
        set {
            this.dtTmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtTmSpecified {
        get {
            return this.dtTmFieldSpecified;
        }
        set {
            this.dtTmFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ATMCommandIdentification1 CmdId {
        get {
            return this.cmdIdField;
        }
        set {
            this.cmdIdField = value;
        }
    }
    
    /// <remarks/>
    public ATMCommandParameters1Choice CmdParams {
        get {
            return this.cmdParamsField;
        }
        set {
            this.cmdParamsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum ATMCommand1Code {
    
    /// <remarks/>
    ABAL,
    
    /// <remarks/>
    ASTS,
    
    /// <remarks/>
    CFGT,
    
    /// <remarks/>
    CCNT,
    
    /// <remarks/>
    DISC,
    
    /// <remarks/>
    SNDM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum TMSContactLevel2Code {
    
    /// <remarks/>
    ASAP,
    
    /// <remarks/>
    CRIT,
    
    /// <remarks/>
    DTIM,
    
    /// <remarks/>
    ENCS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ATMEquipment1 {
    
    private string manfctrField;
    
    private string mdlField;
    
    private string srlNbField;
    
    private string applPrvdrField;
    
    private string applNmField;
    
    private string applVrsnField;
    
    private string apprvlNbField;
    
    private ATMConfigurationParameter1[] cfgtnParamField;
    
    /// <remarks/>
    public string Manfctr {
        get {
            return this.manfctrField;
        }
        set {
            this.manfctrField = value;
        }
    }
    
    /// <remarks/>
    public string Mdl {
        get {
            return this.mdlField;
        }
        set {
            this.mdlField = value;
        }
    }
    
    /// <remarks/>
    public string SrlNb {
        get {
            return this.srlNbField;
        }
        set {
            this.srlNbField = value;
        }
    }
    
    /// <remarks/>
    public string ApplPrvdr {
        get {
            return this.applPrvdrField;
        }
        set {
            this.applPrvdrField = value;
        }
    }
    
    /// <remarks/>
    public string ApplNm {
        get {
            return this.applNmField;
        }
        set {
            this.applNmField = value;
        }
    }
    
    /// <remarks/>
    public string ApplVrsn {
        get {
            return this.applVrsnField;
        }
        set {
            this.applVrsnField = value;
        }
    }
    
    /// <remarks/>
    public string ApprvlNb {
        get {
            return this.apprvlNbField;
        }
        set {
            this.apprvlNbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CfgtnParam")]
    public ATMConfigurationParameter1[] CfgtnParam {
        get {
            return this.cfgtnParamField;
        }
        set {
            this.cfgtnParamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class UTMCoordinates1 {
    
    private string uTMZoneField;
    
    private decimal uTMEstwrdField;
    
    private decimal uTMNrthwrdField;
    
    /// <remarks/>
    public string UTMZone {
        get {
            return this.uTMZoneField;
        }
        set {
            this.uTMZoneField = value;
        }
    }
    
    /// <remarks/>
    public decimal UTMEstwrd {
        get {
            return this.uTMEstwrdField;
        }
        set {
            this.uTMEstwrdField = value;
        }
    }
    
    /// <remarks/>
    public decimal UTMNrthwrd {
        get {
            return this.uTMNrthwrdField;
        }
        set {
            this.uTMNrthwrdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class GeographicCoordinates1 {
    
    private string latField;
    
    private string longField;
    
    /// <remarks/>
    public string Lat {
        get {
            return this.latField;
        }
        set {
            this.latField = value;
        }
    }
    
    /// <remarks/>
    public string Long {
        get {
            return this.longField;
        }
        set {
            this.longField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class GeographicLocation1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GeogcCordints", typeof(GeographicCoordinates1))]
    [System.Xml.Serialization.XmlElementAttribute("UTMCordints", typeof(UTMCoordinates1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class PostalAddress17 {
    
    private string[] adrLineField;
    
    private string strtNmField;
    
    private string bldgNbField;
    
    private string pstCdField;
    
    private string twnNmField;
    
    private string[] ctrySubDvsnField;
    
    private string ctryField;
    
    private GeographicLocation1Choice gLctnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
    public string[] AdrLine {
        get {
            return this.adrLineField;
        }
        set {
            this.adrLineField = value;
        }
    }
    
    /// <remarks/>
    public string StrtNm {
        get {
            return this.strtNmField;
        }
        set {
            this.strtNmField = value;
        }
    }
    
    /// <remarks/>
    public string BldgNb {
        get {
            return this.bldgNbField;
        }
        set {
            this.bldgNbField = value;
        }
    }
    
    /// <remarks/>
    public string PstCd {
        get {
            return this.pstCdField;
        }
        set {
            this.pstCdField = value;
        }
    }
    
    /// <remarks/>
    public string TwnNm {
        get {
            return this.twnNmField;
        }
        set {
            this.twnNmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CtrySubDvsn")]
    public string[] CtrySubDvsn {
        get {
            return this.ctrySubDvsnField;
        }
        set {
            this.ctrySubDvsnField = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    public GeographicLocation1Choice GLctn {
        get {
            return this.gLctnField;
        }
        set {
            this.gLctnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class AutomatedTellerMachine5 {
    
    private string idField;
    
    private string addtlIdField;
    
    private string seqNbField;
    
    private string baseCcyField;
    
    private PostalAddress17 lctnField;
    
    private TransactionEnvironment2Code lctnCtgyField;
    
    private bool lctnCtgyFieldSpecified;
    
    private ATMEquipment1 eqpmntField;
    
    private ATMDevice2Code[] outOfSvcDvcField;
    
    private MessageProtection1Code msgPrtcnField;
    
    private bool msgPrtcnFieldSpecified;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string AddtlId {
        get {
            return this.addtlIdField;
        }
        set {
            this.addtlIdField = value;
        }
    }
    
    /// <remarks/>
    public string SeqNb {
        get {
            return this.seqNbField;
        }
        set {
            this.seqNbField = value;
        }
    }
    
    /// <remarks/>
    public string BaseCcy {
        get {
            return this.baseCcyField;
        }
        set {
            this.baseCcyField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress17 Lctn {
        get {
            return this.lctnField;
        }
        set {
            this.lctnField = value;
        }
    }
    
    /// <remarks/>
    public TransactionEnvironment2Code LctnCtgy {
        get {
            return this.lctnCtgyField;
        }
        set {
            this.lctnCtgyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LctnCtgySpecified {
        get {
            return this.lctnCtgyFieldSpecified;
        }
        set {
            this.lctnCtgyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ATMEquipment1 Eqpmnt {
        get {
            return this.eqpmntField;
        }
        set {
            this.eqpmntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OutOfSvcDvc")]
    public ATMDevice2Code[] OutOfSvcDvc {
        get {
            return this.outOfSvcDvcField;
        }
        set {
            this.outOfSvcDvcField = value;
        }
    }
    
    /// <remarks/>
    public MessageProtection1Code MsgPrtcn {
        get {
            return this.msgPrtcnField;
        }
        set {
            this.msgPrtcnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MsgPrtcnSpecified {
        get {
            return this.msgPrtcnFieldSpecified;
        }
        set {
            this.msgPrtcnFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum TransactionEnvironment2Code {
    
    /// <remarks/>
    PRIV,
    
    /// <remarks/>
    PUBL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum ATMDevice2Code {
    
    /// <remarks/>
    ALRM,
    
    /// <remarks/>
    BRCD,
    
    /// <remarks/>
    CAMR,
    
    /// <remarks/>
    CRDD,
    
    /// <remarks/>
    CRDR,
    
    /// <remarks/>
    CSHD,
    
    /// <remarks/>
    CSHI,
    
    /// <remarks/>
    CSHR,
    
    /// <remarks/>
    CHCK,
    
    /// <remarks/>
    CDIS,
    
    /// <remarks/>
    DPST,
    
    /// <remarks/>
    DPRN,
    
    /// <remarks/>
    DOOR,
    
    /// <remarks/>
    INPM,
    
    /// <remarks/>
    JRNL,
    
    /// <remarks/>
    JPRN,
    
    /// <remarks/>
    SNSR,
    
    /// <remarks/>
    PSBK,
    
    /// <remarks/>
    PINR,
    
    /// <remarks/>
    RPRN,
    
    /// <remarks/>
    SCAN,
    
    /// <remarks/>
    RWDR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum MessageProtection1Code {
    
    /// <remarks/>
    EVLP,
    
    /// <remarks/>
    MACB,
    
    /// <remarks/>
    MACM,
    
    /// <remarks/>
    UNPR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class TerminalHosting1 {
    
    private TransactionEnvironment3Code ctgyField;
    
    private bool ctgyFieldSpecified;
    
    private string idField;
    
    /// <remarks/>
    public TransactionEnvironment3Code Ctgy {
        get {
            return this.ctgyField;
        }
        set {
            this.ctgyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CtgySpecified {
        get {
            return this.ctgyFieldSpecified;
        }
        set {
            this.ctgyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum TransactionEnvironment3Code {
    
    /// <remarks/>
    BRCH,
    
    /// <remarks/>
    MERC,
    
    /// <remarks/>
    OTHR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class Acquirer7 {
    
    private string acqrgInstnField;
    
    private string brnchField;
    
    /// <remarks/>
    public string AcqrgInstn {
        get {
            return this.acqrgInstnField;
        }
        set {
            this.acqrgInstnField = value;
        }
    }
    
    /// <remarks/>
    public string Brnch {
        get {
            return this.brnchField;
        }
        set {
            this.brnchField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ATMEnvironment6 {
    
    private Acquirer7 acqrrField;
    
    private string aTMMgrIdField;
    
    private TerminalHosting1 hstgNttyField;
    
    private AutomatedTellerMachine5 aTMField;
    
    /// <remarks/>
    public Acquirer7 Acqrr {
        get {
            return this.acqrrField;
        }
        set {
            this.acqrrField = value;
        }
    }
    
    /// <remarks/>
    public string ATMMgrId {
        get {
            return this.aTMMgrIdField;
        }
        set {
            this.aTMMgrIdField = value;
        }
    }
    
    /// <remarks/>
    public TerminalHosting1 HstgNtty {
        get {
            return this.hstgNttyField;
        }
        set {
            this.hstgNttyField = value;
        }
    }
    
    /// <remarks/>
    public AutomatedTellerMachine5 ATM {
        get {
            return this.aTMField;
        }
        set {
            this.aTMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ATMDiagnosticResponse1 {
    
    private ATMEnvironment6 envtField;
    
    private ATMCommand1[] cmdField;
    
    /// <remarks/>
    public ATMEnvironment6 Envt {
        get {
            return this.envtField;
        }
        set {
            this.envtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cmd")]
    public ATMCommand1[] Cmd {
        get {
            return this.cmdField;
        }
        set {
            this.cmdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class AlgorithmIdentification14 {
    
    private Algorithm15Code algoField;
    
    private Parameter6 paramField;
    
    /// <remarks/>
    public Algorithm15Code Algo {
        get {
            return this.algoField;
        }
        set {
            this.algoField = value;
        }
    }
    
    /// <remarks/>
    public Parameter6 Param {
        get {
            return this.paramField;
        }
        set {
            this.paramField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum Algorithm15Code {
    
    /// <remarks/>
    EA2C,
    
    /// <remarks/>
    E3DC,
    
    /// <remarks/>
    EA9C,
    
    /// <remarks/>
    EA5C,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class EncryptedContent3 {
    
    private ContentType2Code cnttTpField;
    
    private AlgorithmIdentification14 cnttNcrptnAlgoField;
    
    private byte[] ncrptdDataField;
    
    /// <remarks/>
    public ContentType2Code CnttTp {
        get {
            return this.cnttTpField;
        }
        set {
            this.cnttTpField = value;
        }
    }
    
    /// <remarks/>
    public AlgorithmIdentification14 CnttNcrptnAlgo {
        get {
            return this.cnttNcrptnAlgoField;
        }
        set {
            this.cnttNcrptnAlgoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] NcrptdData {
        get {
            return this.ncrptdDataField;
        }
        set {
            this.ncrptdDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class EnvelopedData4 {
    
    private decimal vrsnField;
    
    private bool vrsnFieldSpecified;
    
    private Recipient4Choice[] rcptField;
    
    private EncryptedContent3 ncrptdCnttField;
    
    /// <remarks/>
    public decimal Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrsnSpecified {
        get {
            return this.vrsnFieldSpecified;
        }
        set {
            this.vrsnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rcpt")]
    public Recipient4Choice[] Rcpt {
        get {
            return this.rcptField;
        }
        set {
            this.rcptField = value;
        }
    }
    
    /// <remarks/>
    public EncryptedContent3 NcrptdCntt {
        get {
            return this.ncrptdCnttField;
        }
        set {
            this.ncrptdCnttField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class ContentInformationType10 {
    
    private ContentType2Code cnttTpField;
    
    private EnvelopedData4 envlpdDataField;
    
    /// <remarks/>
    public ContentType2Code CnttTp {
        get {
            return this.cnttTpField;
        }
        set {
            this.cnttTpField = value;
        }
    }
    
    /// <remarks/>
    public EnvelopedData4 EnvlpdData {
        get {
            return this.envlpdDataField;
        }
        set {
            this.envlpdDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class GenericIdentification77 {
    
    private string idField;
    
    private PartyType12Code tpField;
    
    private PartyType12Code issrField;
    
    private bool issrFieldSpecified;
    
    private string ctryField;
    
    private string shrtNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public PartyType12Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public PartyType12Code Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IssrSpecified {
        get {
            return this.issrFieldSpecified;
        }
        set {
            this.issrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    public string ShrtNm {
        get {
            return this.shrtNmField;
        }
        set {
            this.shrtNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public enum PartyType12Code {
    
    /// <remarks/>
    ACQR,
    
    /// <remarks/>
    ATMG,
    
    /// <remarks/>
    CISP,
    
    /// <remarks/>
    DLIS,
    
    /// <remarks/>
    HSTG,
    
    /// <remarks/>
    ITAG,
    
    /// <remarks/>
    OATM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:caam.006.001.01")]
public partial class Traceability4 {
    
    private GenericIdentification77 rlayIdField;
    
    private string seqNbField;
    
    private System.DateTime tracDtTmInField;
    
    private System.DateTime tracDtTmOutField;
    
    /// <remarks/>
    public GenericIdentification77 RlayId {
        get {
            return this.rlayIdField;
        }
        set {
            this.rlayIdField = value;
        }
    }
    
    /// <remarks/>
    public string SeqNb {
        get {
            return this.seqNbField;
        }
        set {
            this.seqNbField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TracDtTmIn {
        get {
            return this.tracDtTmInField;
        }
        set {
            this.tracDtTmInField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TracDtTmOut {
        get {
            return this.tracDtTmOutField;
        }
        set {
            this.tracDtTmOutField = value;
        }
    }
}
