//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01", IsNullable=false)]
public partial class Document {
    
    private UndertakingApplicationV01 udrtkgApplField;
    
    /// <remarks/>
    public UndertakingApplicationV01 UdrtkgAppl {
        get {
            return this.udrtkgApplField;
        }
        set {
            this.udrtkgApplField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class UndertakingApplicationV01 {
    
    private Undertaking1 udrtkgApplDtlsField;
    
    private string[] instrsToBkField;
    
    private PartyAndSignature2 dgtlSgntrField;
    
    /// <remarks/>
    public Undertaking1 UdrtkgApplDtls {
        get {
            return this.udrtkgApplDtlsField;
        }
        set {
            this.udrtkgApplDtlsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InstrsToBk")]
    public string[] InstrsToBk {
        get {
            return this.instrsToBkField;
        }
        set {
            this.instrsToBkField = value;
        }
    }
    
    /// <remarks/>
    public PartyAndSignature2 DgtlSgntr {
        get {
            return this.dgtlSgntrField;
        }
        set {
            this.dgtlSgntrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Undertaking1 {
    
    private string applcntRefNbField;
    
    private string purpField;
    
    private UndertakingName1Code nmField;
    
    private UndertakingType1Choice tpField;
    
    private PartyIdentification43 oblgrField;
    
    private PartyIdentification43[] applcntField;
    
    private PartyIdentification43 issrField;
    
    private PartyIdentification43[] bnfcryField;
    
    private PartyIdentification43 advsgPtyField;
    
    private PartyIdentification43 scndAdvsgPtyField;
    
    private PartyIdentification43 cnfrmrField;
    
    private bool confIndField;
    
    private bool confIndFieldSpecified;
    
    private bool cntrUdrtkgIndField;
    
    private Undertaking2 cntrUdrtkgField;
    
    private UndertakingAmount1 udrtkgAmtField;
    
    private ExpiryDetails2 xpryDtlsField;
    
    private PartyAndType1[] addtlPtyField;
    
    private GovernanceRules1 govncRulesAndLawField;
    
    private UnderlyingTradeTransaction1[] undrlygTxField;
    
    private Presentation4 presntnDtlsField;
    
    private UndertakingWording1 udrtkgWrdgField;
    
    private bool mltplDmndIndField;
    
    private bool mltplDmndIndFieldSpecified;
    
    private bool prtlDmndIndField;
    
    private bool prtlDmndIndFieldSpecified;
    
    private bool trfIndField;
    
    private bool trfIndFieldSpecified;
    
    private string trfChrgsPyblByField;
    
    private string confChrgsPyblByField;
    
    private AutomaticVariation1[] automtcAmtVartnField;
    
    private CommunicationChannel1 dlvryChanlField;
    
    private CashAccount28 oblgrLbltyAcctField;
    
    private CashAccount28 oblgrChrgAcctField;
    
    private CashAccount28 oblgrSttlmAcctField;
    
    private Document9[] nclsdFileField;
    
    private string[] addtlApplInfField;
    
    /// <remarks/>
    public string ApplcntRefNb {
        get {
            return this.applcntRefNbField;
        }
        set {
            this.applcntRefNbField = value;
        }
    }
    
    /// <remarks/>
    public string Purp {
        get {
            return this.purpField;
        }
        set {
            this.purpField = value;
        }
    }
    
    /// <remarks/>
    public UndertakingName1Code Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public UndertakingType1Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification43 Oblgr {
        get {
            return this.oblgrField;
        }
        set {
            this.oblgrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Applcnt")]
    public PartyIdentification43[] Applcnt {
        get {
            return this.applcntField;
        }
        set {
            this.applcntField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification43 Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Bnfcry")]
    public PartyIdentification43[] Bnfcry {
        get {
            return this.bnfcryField;
        }
        set {
            this.bnfcryField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification43 AdvsgPty {
        get {
            return this.advsgPtyField;
        }
        set {
            this.advsgPtyField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification43 ScndAdvsgPty {
        get {
            return this.scndAdvsgPtyField;
        }
        set {
            this.scndAdvsgPtyField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification43 Cnfrmr {
        get {
            return this.cnfrmrField;
        }
        set {
            this.cnfrmrField = value;
        }
    }
    
    /// <remarks/>
    public bool ConfInd {
        get {
            return this.confIndField;
        }
        set {
            this.confIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConfIndSpecified {
        get {
            return this.confIndFieldSpecified;
        }
        set {
            this.confIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool CntrUdrtkgInd {
        get {
            return this.cntrUdrtkgIndField;
        }
        set {
            this.cntrUdrtkgIndField = value;
        }
    }
    
    /// <remarks/>
    public Undertaking2 CntrUdrtkg {
        get {
            return this.cntrUdrtkgField;
        }
        set {
            this.cntrUdrtkgField = value;
        }
    }
    
    /// <remarks/>
    public UndertakingAmount1 UdrtkgAmt {
        get {
            return this.udrtkgAmtField;
        }
        set {
            this.udrtkgAmtField = value;
        }
    }
    
    /// <remarks/>
    public ExpiryDetails2 XpryDtls {
        get {
            return this.xpryDtlsField;
        }
        set {
            this.xpryDtlsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlPty")]
    public PartyAndType1[] AddtlPty {
        get {
            return this.addtlPtyField;
        }
        set {
            this.addtlPtyField = value;
        }
    }
    
    /// <remarks/>
    public GovernanceRules1 GovncRulesAndLaw {
        get {
            return this.govncRulesAndLawField;
        }
        set {
            this.govncRulesAndLawField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UndrlygTx")]
    public UnderlyingTradeTransaction1[] UndrlygTx {
        get {
            return this.undrlygTxField;
        }
        set {
            this.undrlygTxField = value;
        }
    }
    
    /// <remarks/>
    public Presentation4 PresntnDtls {
        get {
            return this.presntnDtlsField;
        }
        set {
            this.presntnDtlsField = value;
        }
    }
    
    /// <remarks/>
    public UndertakingWording1 UdrtkgWrdg {
        get {
            return this.udrtkgWrdgField;
        }
        set {
            this.udrtkgWrdgField = value;
        }
    }
    
    /// <remarks/>
    public bool MltplDmndInd {
        get {
            return this.mltplDmndIndField;
        }
        set {
            this.mltplDmndIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MltplDmndIndSpecified {
        get {
            return this.mltplDmndIndFieldSpecified;
        }
        set {
            this.mltplDmndIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool PrtlDmndInd {
        get {
            return this.prtlDmndIndField;
        }
        set {
            this.prtlDmndIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrtlDmndIndSpecified {
        get {
            return this.prtlDmndIndFieldSpecified;
        }
        set {
            this.prtlDmndIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool TrfInd {
        get {
            return this.trfIndField;
        }
        set {
            this.trfIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TrfIndSpecified {
        get {
            return this.trfIndFieldSpecified;
        }
        set {
            this.trfIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string TrfChrgsPyblBy {
        get {
            return this.trfChrgsPyblByField;
        }
        set {
            this.trfChrgsPyblByField = value;
        }
    }
    
    /// <remarks/>
    public string ConfChrgsPyblBy {
        get {
            return this.confChrgsPyblByField;
        }
        set {
            this.confChrgsPyblByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AutomtcAmtVartn")]
    public AutomaticVariation1[] AutomtcAmtVartn {
        get {
            return this.automtcAmtVartnField;
        }
        set {
            this.automtcAmtVartnField = value;
        }
    }
    
    /// <remarks/>
    public CommunicationChannel1 DlvryChanl {
        get {
            return this.dlvryChanlField;
        }
        set {
            this.dlvryChanlField = value;
        }
    }
    
    /// <remarks/>
    public CashAccount28 OblgrLbltyAcct {
        get {
            return this.oblgrLbltyAcctField;
        }
        set {
            this.oblgrLbltyAcctField = value;
        }
    }
    
    /// <remarks/>
    public CashAccount28 OblgrChrgAcct {
        get {
            return this.oblgrChrgAcctField;
        }
        set {
            this.oblgrChrgAcctField = value;
        }
    }
    
    /// <remarks/>
    public CashAccount28 OblgrSttlmAcct {
        get {
            return this.oblgrSttlmAcctField;
        }
        set {
            this.oblgrSttlmAcctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NclsdFile")]
    public Document9[] NclsdFile {
        get {
            return this.nclsdFileField;
        }
        set {
            this.nclsdFileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlApplInf")]
    public string[] AddtlApplInf {
        get {
            return this.addtlApplInfField;
        }
        set {
            this.addtlApplInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public enum UndertakingName1Code {
    
    /// <remarks/>
    STBY,
    
    /// <remarks/>
    DGAR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class UndertakingType1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class GenericIdentification1 {
    
    private string idField;
    
    private string schmeNmField;
    
    private string issrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class PartyAndSignature2 {
    
    private PartyIdentification43 ptyField;
    
    private System.Xml.XmlElement sgntrField;
    
    /// <remarks/>
    public PartyIdentification43 Pty {
        get {
            return this.ptyField;
        }
        set {
            this.ptyField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Sgntr {
        get {
            return this.sgntrField;
        }
        set {
            this.sgntrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class PartyIdentification43 {
    
    private string nmField;
    
    private PostalAddress6 pstlAdrField;
    
    private Party11Choice idField;
    
    private string ctryOfResField;
    
    private ContactDetails2 ctctDtlsField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress6 PstlAdr {
        get {
            return this.pstlAdrField;
        }
        set {
            this.pstlAdrField = value;
        }
    }
    
    /// <remarks/>
    public Party11Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string CtryOfRes {
        get {
            return this.ctryOfResField;
        }
        set {
            this.ctryOfResField = value;
        }
    }
    
    /// <remarks/>
    public ContactDetails2 CtctDtls {
        get {
            return this.ctctDtlsField;
        }
        set {
            this.ctctDtlsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class PostalAddress6 {
    
    private AddressType2Code adrTpField;
    
    private bool adrTpFieldSpecified;
    
    private string deptField;
    
    private string subDeptField;
    
    private string strtNmField;
    
    private string bldgNbField;
    
    private string pstCdField;
    
    private string twnNmField;
    
    private string ctrySubDvsnField;
    
    private string ctryField;
    
    private string[] adrLineField;
    
    /// <remarks/>
    public AddressType2Code AdrTp {
        get {
            return this.adrTpField;
        }
        set {
            this.adrTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AdrTpSpecified {
        get {
            return this.adrTpFieldSpecified;
        }
        set {
            this.adrTpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Dept {
        get {
            return this.deptField;
        }
        set {
            this.deptField = value;
        }
    }
    
    /// <remarks/>
    public string SubDept {
        get {
            return this.subDeptField;
        }
        set {
            this.subDeptField = value;
        }
    }
    
    /// <remarks/>
    public string StrtNm {
        get {
            return this.strtNmField;
        }
        set {
            this.strtNmField = value;
        }
    }
    
    /// <remarks/>
    public string BldgNb {
        get {
            return this.bldgNbField;
        }
        set {
            this.bldgNbField = value;
        }
    }
    
    /// <remarks/>
    public string PstCd {
        get {
            return this.pstCdField;
        }
        set {
            this.pstCdField = value;
        }
    }
    
    /// <remarks/>
    public string TwnNm {
        get {
            return this.twnNmField;
        }
        set {
            this.twnNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsn {
        get {
            return this.ctrySubDvsnField;
        }
        set {
            this.ctrySubDvsnField = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
    public string[] AdrLine {
        get {
            return this.adrLineField;
        }
        set {
            this.adrLineField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public enum AddressType2Code {
    
    /// <remarks/>
    ADDR,
    
    /// <remarks/>
    PBOX,
    
    /// <remarks/>
    HOME,
    
    /// <remarks/>
    BIZZ,
    
    /// <remarks/>
    MLTO,
    
    /// <remarks/>
    DLVY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Party11Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(OrganisationIdentification8))]
    [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(PersonIdentification5))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class OrganisationIdentification8 {
    
    private string anyBICField;
    
    private GenericOrganisationIdentification1[] othrField;
    
    /// <remarks/>
    public string AnyBIC {
        get {
            return this.anyBICField;
        }
        set {
            this.anyBICField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Othr")]
    public GenericOrganisationIdentification1[] Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class GenericOrganisationIdentification1 {
    
    private string idField;
    
    private OrganisationIdentificationSchemeName1Choice schmeNmField;
    
    private string issrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public OrganisationIdentificationSchemeName1Choice SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class OrganisationIdentificationSchemeName1Choice {
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class PersonIdentification5 {
    
    private DateAndPlaceOfBirth dtAndPlcOfBirthField;
    
    private GenericPersonIdentification1[] othrField;
    
    /// <remarks/>
    public DateAndPlaceOfBirth DtAndPlcOfBirth {
        get {
            return this.dtAndPlcOfBirthField;
        }
        set {
            this.dtAndPlcOfBirthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Othr")]
    public GenericPersonIdentification1[] Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class DateAndPlaceOfBirth {
    
    private System.DateTime birthDtField;
    
    private string prvcOfBirthField;
    
    private string cityOfBirthField;
    
    private string ctryOfBirthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BirthDt {
        get {
            return this.birthDtField;
        }
        set {
            this.birthDtField = value;
        }
    }
    
    /// <remarks/>
    public string PrvcOfBirth {
        get {
            return this.prvcOfBirthField;
        }
        set {
            this.prvcOfBirthField = value;
        }
    }
    
    /// <remarks/>
    public string CityOfBirth {
        get {
            return this.cityOfBirthField;
        }
        set {
            this.cityOfBirthField = value;
        }
    }
    
    /// <remarks/>
    public string CtryOfBirth {
        get {
            return this.ctryOfBirthField;
        }
        set {
            this.ctryOfBirthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class GenericPersonIdentification1 {
    
    private string idField;
    
    private PersonIdentificationSchemeName1Choice schmeNmField;
    
    private string issrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public PersonIdentificationSchemeName1Choice SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class PersonIdentificationSchemeName1Choice {
    
    private string itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class ContactDetails2 {
    
    private NamePrefix1Code nmPrfxField;
    
    private bool nmPrfxFieldSpecified;
    
    private string nmField;
    
    private string phneNbField;
    
    private string mobNbField;
    
    private string faxNbField;
    
    private string emailAdrField;
    
    private string othrField;
    
    /// <remarks/>
    public NamePrefix1Code NmPrfx {
        get {
            return this.nmPrfxField;
        }
        set {
            this.nmPrfxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NmPrfxSpecified {
        get {
            return this.nmPrfxFieldSpecified;
        }
        set {
            this.nmPrfxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public string PhneNb {
        get {
            return this.phneNbField;
        }
        set {
            this.phneNbField = value;
        }
    }
    
    /// <remarks/>
    public string MobNb {
        get {
            return this.mobNbField;
        }
        set {
            this.mobNbField = value;
        }
    }
    
    /// <remarks/>
    public string FaxNb {
        get {
            return this.faxNbField;
        }
        set {
            this.faxNbField = value;
        }
    }
    
    /// <remarks/>
    public string EmailAdr {
        get {
            return this.emailAdrField;
        }
        set {
            this.emailAdrField = value;
        }
    }
    
    /// <remarks/>
    public string Othr {
        get {
            return this.othrField;
        }
        set {
            this.othrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public enum NamePrefix1Code {
    
    /// <remarks/>
    DOCT,
    
    /// <remarks/>
    MIST,
    
    /// <remarks/>
    MISS,
    
    /// <remarks/>
    MADM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class UndertakingDocumentType1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Document9 {
    
    private UndertakingDocumentType1Choice tpField;
    
    private string idField;
    
    private DocumentFormat1Choice frmtField;
    
    private byte[] nclsrField;
    
    private PartyAndSignature2 dgtlSgntrField;
    
    /// <remarks/>
    public UndertakingDocumentType1Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public DocumentFormat1Choice Frmt {
        get {
            return this.frmtField;
        }
        set {
            this.frmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Nclsr {
        get {
            return this.nclsrField;
        }
        set {
            this.nclsrField = value;
        }
    }
    
    /// <remarks/>
    public PartyAndSignature2 DgtlSgntr {
        get {
            return this.dgtlSgntrField;
        }
        set {
            this.dgtlSgntrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class DocumentFormat1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class AccountSchemeName1Choice {
    
    private string itemField;
    
    private ItemChoiceType4 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType4 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01", IncludeInSchema=false)]
public enum ItemChoiceType4 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class GenericAccountIdentification1 {
    
    private string idField;
    
    private AccountSchemeName1Choice schmeNmField;
    
    private string issrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public AccountSchemeName1Choice SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class AccountIdentification4Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("IBAN", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(GenericAccountIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class CashAccount28 {
    
    private AccountIdentification4Choice idField;
    
    private string ccyField;
    
    private string nmField;
    
    /// <remarks/>
    public AccountIdentification4Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class CommunicationChannel1 {
    
    private string mtdField;
    
    private PartyType1Choice dlvrToPtyTpField;
    
    private string dlvrToNmField;
    
    private PostalAddress6 dlvrToAdrField;
    
    /// <remarks/>
    public string Mtd {
        get {
            return this.mtdField;
        }
        set {
            this.mtdField = value;
        }
    }
    
    /// <remarks/>
    public PartyType1Choice DlvrToPtyTp {
        get {
            return this.dlvrToPtyTpField;
        }
        set {
            this.dlvrToPtyTpField = value;
        }
    }
    
    /// <remarks/>
    public string DlvrToNm {
        get {
            return this.dlvrToNmField;
        }
        set {
            this.dlvrToNmField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress6 DlvrToAdr {
        get {
            return this.dlvrToAdrField;
        }
        set {
            this.dlvrToAdrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class PartyType1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class UndertakingDocumentType2Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Document10 {
    
    private UndertakingDocumentType2Choice docTpField;
    
    private Channel1Choice presntnChanlField;
    
    private DocumentFormat1Choice docFrmtField;
    
    private bool cpyIndField;
    
    private bool cpyIndFieldSpecified;
    
    private bool sgndIndField;
    
    private bool sgndIndFieldSpecified;
    
    /// <remarks/>
    public UndertakingDocumentType2Choice DocTp {
        get {
            return this.docTpField;
        }
        set {
            this.docTpField = value;
        }
    }
    
    /// <remarks/>
    public Channel1Choice PresntnChanl {
        get {
            return this.presntnChanlField;
        }
        set {
            this.presntnChanlField = value;
        }
    }
    
    /// <remarks/>
    public DocumentFormat1Choice DocFrmt {
        get {
            return this.docFrmtField;
        }
        set {
            this.docFrmtField = value;
        }
    }
    
    /// <remarks/>
    public bool CpyInd {
        get {
            return this.cpyIndField;
        }
        set {
            this.cpyIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CpyIndSpecified {
        get {
            return this.cpyIndFieldSpecified;
        }
        set {
            this.cpyIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool SgndInd {
        get {
            return this.sgndIndField;
        }
        set {
            this.sgndIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SgndIndSpecified {
        get {
            return this.sgndIndFieldSpecified;
        }
        set {
            this.sgndIndFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Channel1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class DateInformation1 {
    
    private System.DateTime startDtField;
    
    private string frqcyField;
    
    private decimal nbField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime StartDt {
        get {
            return this.startDtField;
        }
        set {
            this.startDtField = value;
        }
    }
    
    /// <remarks/>
    public string Frqcy {
        get {
            return this.frqcyField;
        }
        set {
            this.frqcyField = value;
        }
    }
    
    /// <remarks/>
    public decimal Nb {
        get {
            return this.nbField;
        }
        set {
            this.nbField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class FixedOrRecurrentDate1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FxdDt", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("RcrntDt", typeof(DateInformation1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Trigger1 {
    
    private FixedOrRecurrentDate1Choice dtChcField;
    
    private Document10[] dcmntryEvtField;
    
    /// <remarks/>
    public FixedOrRecurrentDate1Choice DtChc {
        get {
            return this.dtChcField;
        }
        set {
            this.dtChcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DcmntryEvt")]
    public Document10[] DcmntryEvt {
        get {
            return this.dcmntryEvtField;
        }
        set {
            this.dcmntryEvtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Percentage1 {
    
    private decimal rateField;
    
    private string rltvToField;
    
    /// <remarks/>
    public decimal Rate {
        get {
            return this.rateField;
        }
        set {
            this.rateField = value;
        }
    }
    
    /// <remarks/>
    public string RltvTo {
        get {
            return this.rltvToField;
        }
        set {
            this.rltvToField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class UndertakingAmount4 {
    
    private ActiveCurrencyAndAmount vartnAmtField;
    
    private ActiveCurrencyAndAmount balAmtField;
    
    /// <remarks/>
    public ActiveCurrencyAndAmount VartnAmt {
        get {
            return this.vartnAmtField;
        }
        set {
            this.vartnAmtField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount BalAmt {
        get {
            return this.balAmtField;
        }
        set {
            this.balAmtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class ActiveCurrencyAndAmount {
    
    private string ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class AmountOrPercentage1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DfndAmt", typeof(UndertakingAmount4))]
    [System.Xml.Serialization.XmlElementAttribute("PctgAmt", typeof(Percentage1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class AmountAndTrigger1 {
    
    private string idField;
    
    private AmountOrPercentage1Choice amtDtlsChcField;
    
    private Trigger1[] trggrField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public AmountOrPercentage1Choice AmtDtlsChc {
        get {
            return this.amtDtlsChcField;
        }
        set {
            this.amtDtlsChcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Trggr")]
    public Trigger1[] Trggr {
        get {
            return this.trggrField;
        }
        set {
            this.trggrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class AutomaticVariation1 {
    
    private string idField;
    
    private VariationType1Code tpField;
    
    private AmountAndTrigger1[] amtAndTrggrField;
    
    private string[] addtlInfField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public VariationType1Code Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AmtAndTrggr")]
    public AmountAndTrigger1[] AmtAndTrggr {
        get {
            return this.amtAndTrggrField;
        }
        set {
            this.amtAndTrggrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
    public string[] AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public enum VariationType1Code {
    
    /// <remarks/>
    DECR,
    
    /// <remarks/>
    INCR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class NarrativeType1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Narrative1 {
    
    private NarrativeType1Choice tpField;
    
    private string[] txtField;
    
    /// <remarks/>
    public NarrativeType1Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Txt")]
    public string[] Txt {
        get {
            return this.txtField;
        }
        set {
            this.txtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class ModelFormIdentification1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class ModelFormIdentification1 {
    
    private ModelFormIdentification1Choice idField;
    
    private string vrsnField;
    
    /// <remarks/>
    public ModelFormIdentification1Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Vrsn {
        get {
            return this.vrsnField;
        }
        set {
            this.vrsnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class UndertakingWording1 {
    
    private ModelFormIdentification1 mdlFormField;
    
    private string reqdWrdgLangField;
    
    private Narrative1[] udrtkgTermsAndCondsField;
    
    /// <remarks/>
    public ModelFormIdentification1 MdlForm {
        get {
            return this.mdlFormField;
        }
        set {
            this.mdlFormField = value;
        }
    }
    
    /// <remarks/>
    public string ReqdWrdgLang {
        get {
            return this.reqdWrdgLangField;
        }
        set {
            this.reqdWrdgLangField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UdrtkgTermsAndConds")]
    public Narrative1[] UdrtkgTermsAndConds {
        get {
            return this.udrtkgTermsAndCondsField;
        }
        set {
            this.udrtkgTermsAndCondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Presentation3 {
    
    private DocumentFormat1Choice frmtField;
    
    private Channel1Choice chanlField;
    
    private string adrField;
    
    /// <remarks/>
    public DocumentFormat1Choice Frmt {
        get {
            return this.frmtField;
        }
        set {
            this.frmtField = value;
        }
    }
    
    /// <remarks/>
    public Channel1Choice Chanl {
        get {
            return this.chanlField;
        }
        set {
            this.chanlField = value;
        }
    }
    
    /// <remarks/>
    public string Adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class PresentationDocumentFormat1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Document11 {
    
    private PresentationDocumentFormat1Choice tpField;
    
    private string wrdgField;
    
    private Presentation3[] elctrncDtlsField;
    
    /// <remarks/>
    public PresentationDocumentFormat1Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Wrdg {
        get {
            return this.wrdgField;
        }
        set {
            this.wrdgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ElctrncDtls")]
    public Presentation3[] ElctrncDtls {
        get {
            return this.elctrncDtlsField;
        }
        set {
            this.elctrncDtlsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class PresentationMedium1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(PresentationMedium1Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public enum PresentationMedium1Code {
    
    /// <remarks/>
    BOTH,
    
    /// <remarks/>
    ELEC,
    
    /// <remarks/>
    PAPR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Presentation4 {
    
    private PresentationMedium1Choice mdmField;
    
    private Document11[] docField;
    
    private string[] addtlInfField;
    
    /// <remarks/>
    public PresentationMedium1Choice Mdm {
        get {
            return this.mdmField;
        }
        set {
            this.mdmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Doc")]
    public Document11[] Doc {
        get {
            return this.docField;
        }
        set {
            this.docField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
    public string[] AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class UnderlyingTradeTransactionType1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class UnderlyingTradeTransaction1 {
    
    private UnderlyingTradeTransactionType1Choice tpField;
    
    private string idField;
    
    private System.DateTime txDtField;
    
    private bool txDtFieldSpecified;
    
    private System.DateTime tndrClsgDtField;
    
    private bool tndrClsgDtFieldSpecified;
    
    private ActiveCurrencyAndAmount txAmtField;
    
    private decimal ctrctAmtPctgField;
    
    private bool ctrctAmtPctgFieldSpecified;
    
    private string[] addtlInfField;
    
    /// <remarks/>
    public UnderlyingTradeTransactionType1Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TxDt {
        get {
            return this.txDtField;
        }
        set {
            this.txDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TxDtSpecified {
        get {
            return this.txDtFieldSpecified;
        }
        set {
            this.txDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TndrClsgDt {
        get {
            return this.tndrClsgDtField;
        }
        set {
            this.tndrClsgDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TndrClsgDtSpecified {
        get {
            return this.tndrClsgDtFieldSpecified;
        }
        set {
            this.tndrClsgDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount TxAmt {
        get {
            return this.txAmtField;
        }
        set {
            this.txAmtField = value;
        }
    }
    
    /// <remarks/>
    public decimal CtrctAmtPctg {
        get {
            return this.ctrctAmtPctgField;
        }
        set {
            this.ctrctAmtPctgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CtrctAmtPctgSpecified {
        get {
            return this.ctrctAmtPctgFieldSpecified;
        }
        set {
            this.ctrctAmtPctgFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
    public string[] AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class PartyAndType1 {
    
    private PartyType1Choice tpField;
    
    private PartyIdentification43 ptyField;
    
    /// <remarks/>
    public PartyType1Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification43 Pty {
        get {
            return this.ptyField;
        }
        set {
            this.ptyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class CountrySubdivision1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Location1 {
    
    private string ctryField;
    
    private CountrySubdivision1Choice ctrySubDvsnField;
    
    private string[] txtField;
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
    
    /// <remarks/>
    public CountrySubdivision1Choice CtrySubDvsn {
        get {
            return this.ctrySubDvsnField;
        }
        set {
            this.ctrySubDvsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Txt")]
    public string[] Txt {
        get {
            return this.txtField;
        }
        set {
            this.txtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class GovernanceIdentification1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(GovernanceIdentification1Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public enum GovernanceIdentification1Code {
    
    /// <remarks/>
    ISPR,
    
    /// <remarks/>
    NONE,
    
    /// <remarks/>
    UCPR,
    
    /// <remarks/>
    URDG,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class GovernanceRules1 {
    
    private GovernanceIdentification1Choice ruleIdField;
    
    private Location1 aplblLawField;
    
    private Location1[] jursdctnField;
    
    /// <remarks/>
    public GovernanceIdentification1Choice RuleId {
        get {
            return this.ruleIdField;
        }
        set {
            this.ruleIdField = value;
        }
    }
    
    /// <remarks/>
    public Location1 AplblLaw {
        get {
            return this.aplblLawField;
        }
        set {
            this.aplblLawField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Jursdctn")]
    public Location1[] Jursdctn {
        get {
            return this.jursdctnField;
        }
        set {
            this.jursdctnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class UndertakingAmount1 {
    
    private ActiveCurrencyAndAmount amtField;
    
    private decimal plusTlrnceField;
    
    private bool plusTlrnceFieldSpecified;
    
    private string[] addtlInfField;
    
    /// <remarks/>
    public ActiveCurrencyAndAmount Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <remarks/>
    public decimal PlusTlrnce {
        get {
            return this.plusTlrnceField;
        }
        set {
            this.plusTlrnceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PlusTlrnceSpecified {
        get {
            return this.plusTlrnceFieldSpecified;
        }
        set {
            this.plusTlrnceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
    public string[] AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class CommunicationMethod1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class NonExtension1 {
    
    private decimal ntfctnPrdField;
    
    private bool ntfctnPrdFieldSpecified;
    
    private CommunicationMethod1Choice ntfctnMtdField;
    
    private PartyType1Choice ntfctnRcptTpField;
    
    private string ntfctnRcptNmField;
    
    private PostalAddress6 ntfctnRcptAdrField;
    
    /// <remarks/>
    public decimal NtfctnPrd {
        get {
            return this.ntfctnPrdField;
        }
        set {
            this.ntfctnPrdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NtfctnPrdSpecified {
        get {
            return this.ntfctnPrdFieldSpecified;
        }
        set {
            this.ntfctnPrdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public CommunicationMethod1Choice NtfctnMtd {
        get {
            return this.ntfctnMtdField;
        }
        set {
            this.ntfctnMtdField = value;
        }
    }
    
    /// <remarks/>
    public PartyType1Choice NtfctnRcptTp {
        get {
            return this.ntfctnRcptTpField;
        }
        set {
            this.ntfctnRcptTpField = value;
        }
    }
    
    /// <remarks/>
    public string NtfctnRcptNm {
        get {
            return this.ntfctnRcptNmField;
        }
        set {
            this.ntfctnRcptNmField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress6 NtfctnRcptAdr {
        get {
            return this.ntfctnRcptAdrField;
        }
        set {
            this.ntfctnRcptAdrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class AutoExtend1Choice {
    
    private object itemField;
    
    private ItemChoiceType3 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Days", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("Mnths", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("Yrs", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType3 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01", IncludeInSchema=false)]
public enum ItemChoiceType3 {
    
    /// <remarks/>
    Days,
    
    /// <remarks/>
    Dt,
    
    /// <remarks/>
    Mnths,
    
    /// <remarks/>
    Yrs,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class AutoExtension1 {
    
    private AutoExtend1Choice prdField;
    
    private System.DateTime fnlXpryDtField;
    
    private bool fnlXpryDtFieldSpecified;
    
    private NonExtension1[] nonXtnsnNtfctnField;
    
    /// <remarks/>
    public AutoExtend1Choice Prd {
        get {
            return this.prdField;
        }
        set {
            this.prdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FnlXpryDt {
        get {
            return this.fnlXpryDtField;
        }
        set {
            this.fnlXpryDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FnlXpryDtSpecified {
        get {
            return this.fnlXpryDtFieldSpecified;
        }
        set {
            this.fnlXpryDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NonXtnsnNtfctn")]
    public NonExtension1[] NonXtnsnNtfctn {
        get {
            return this.nonXtnsnNtfctnField;
        }
        set {
            this.nonXtnsnNtfctnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class DateAndDateTimeChoice {
    
    private System.DateTime itemField;
    
    private ItemChoiceType2 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("DtTm", typeof(System.DateTime))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public System.DateTime Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType2 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01", IncludeInSchema=false)]
public enum ItemChoiceType2 {
    
    /// <remarks/>
    Dt,
    
    /// <remarks/>
    DtTm,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class ExpiryTerms2 {
    
    private DateAndDateTimeChoice dtTmField;
    
    private AutoExtension1 autoXtnsnField;
    
    private string condField;
    
    private bool opnEnddIndField;
    
    private bool opnEnddIndFieldSpecified;
    
    /// <remarks/>
    public DateAndDateTimeChoice DtTm {
        get {
            return this.dtTmField;
        }
        set {
            this.dtTmField = value;
        }
    }
    
    /// <remarks/>
    public AutoExtension1 AutoXtnsn {
        get {
            return this.autoXtnsnField;
        }
        set {
            this.autoXtnsnField = value;
        }
    }
    
    /// <remarks/>
    public string Cond {
        get {
            return this.condField;
        }
        set {
            this.condField = value;
        }
    }
    
    /// <remarks/>
    public bool OpnEnddInd {
        get {
            return this.opnEnddIndField;
        }
        set {
            this.opnEnddIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OpnEnddIndSpecified {
        get {
            return this.opnEnddIndFieldSpecified;
        }
        set {
            this.opnEnddIndFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class ExpiryDetails2 {
    
    private ExpiryTerms2 xpryTermsField;
    
    private string[] addtlXpryInfField;
    
    /// <remarks/>
    public ExpiryTerms2 XpryTerms {
        get {
            return this.xpryTermsField;
        }
        set {
            this.xpryTermsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlXpryInf")]
    public string[] AddtlXpryInf {
        get {
            return this.addtlXpryInfField;
        }
        set {
            this.addtlXpryInfField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:tsin.005.001.01")]
public partial class Undertaking2 {
    
    private UndertakingName1Code nmField;
    
    private bool nmFieldSpecified;
    
    private PartyIdentification43 bnfcryField;
    
    private ExpiryDetails2 xpryDtlsField;
    
    private UndertakingAmount1 cntrUdrtkgAmtField;
    
    private string confChrgsPyblByField;
    
    private GovernanceRules1 govncRulesAndLawField;
    
    private bool stdClmDocIndField;
    
    private bool stdClmDocIndFieldSpecified;
    
    private string[] addtlInfField;
    
    /// <remarks/>
    public UndertakingName1Code Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NmSpecified {
        get {
            return this.nmFieldSpecified;
        }
        set {
            this.nmFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification43 Bnfcry {
        get {
            return this.bnfcryField;
        }
        set {
            this.bnfcryField = value;
        }
    }
    
    /// <remarks/>
    public ExpiryDetails2 XpryDtls {
        get {
            return this.xpryDtlsField;
        }
        set {
            this.xpryDtlsField = value;
        }
    }
    
    /// <remarks/>
    public UndertakingAmount1 CntrUdrtkgAmt {
        get {
            return this.cntrUdrtkgAmtField;
        }
        set {
            this.cntrUdrtkgAmtField = value;
        }
    }
    
    /// <remarks/>
    public string ConfChrgsPyblBy {
        get {
            return this.confChrgsPyblByField;
        }
        set {
            this.confChrgsPyblByField = value;
        }
    }
    
    /// <remarks/>
    public GovernanceRules1 GovncRulesAndLaw {
        get {
            return this.govncRulesAndLawField;
        }
        set {
            this.govncRulesAndLawField = value;
        }
    }
    
    /// <remarks/>
    public bool StdClmDocInd {
        get {
            return this.stdClmDocIndField;
        }
        set {
            this.stdClmDocIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StdClmDocIndSpecified {
        get {
            return this.stdClmDocIndFieldSpecified;
        }
        set {
            this.stdClmDocIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
    public string[] AddtlInf {
        get {
            return this.addtlInfField;
        }
        set {
            this.addtlInfField = value;
        }
    }
}
