// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Zent.Iso20022.ClassGeneration.Templates.Xml
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Zent.Iso20022.ModelGeneration.Models.Interfaces;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class InheritorClassTemplate : InheritorClassTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("namespace ");
            
            #line 7 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 9 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 if(ClassElement.Description is not null){ 
            
            #line default
            #line hidden
            this.Write("/// <summary>\r\n");
            
            #line 11 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 var classSummaryLines = ClassElement.Description.Split(new[] { "Environment.NewLine", "\r\n", "\n" }, StringSplitOptions.None); 
            
            #line default
            #line hidden
            
            #line 12 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 var lastsummary = classSummaryLines.Last(); 
            
            #line default
            #line hidden
            
            #line 13 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 foreach(var line in classSummaryLines ){ 
            
            #line default
            #line hidden
            this.Write("/// ");
            
            #line 14 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            
            #line 14 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 if(!line.Equals(lastsummary)){ 
            
            #line default
            #line hidden
            this.Write("<br/>\r\n");
            
            #line 15 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 16 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n/// </summary>\r\n");
            
            #line 19 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("[System.CodeDom.Compiler.GeneratedCodeAttribute(\"");
            
            #line 20 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Generator));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 20 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SoftwareVersion));
            
            #line default
            #line hidden
            this.Write("\")]\r\n[System.ComponentModel.Description(\"This has been generated on the Model ver" +
                    "sion: ");
            
            #line 21 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVersion));
            
            #line default
            #line hidden
            this.Write("\")]\r\n[System.SerializableAttribute()]\r\n[System.Diagnostics.DebuggerStepThroughAtt" +
                    "ribute()]\r\n[System.ComponentModel.DesignerCategoryAttribute(\"code\")]\r\n[System.Xm" +
                    "l.Serialization.XmlTypeAttribute(Namespace=\"urn:iso:std:iso:20022:tech:xsd:");
            
            #line 25 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SchemaVersion));
            
            #line default
            #line hidden
            this.Write("\")]\r\npublic partial class ");
            
            #line 26 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassElement.ClassName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 26 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassElement.BaseClassName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 28 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 var lastProperty = ClassElement.Properties.Last(); 
            
            #line default
            #line hidden
            
            #line 29 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 foreach(var thisProperty in ClassElement.Properties){ 
            
            #line default
            #line hidden
            
            #line 30 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 if(thisProperty.Description is not null){ 
            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n");
            
            #line 32 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 var lines = thisProperty.Description.Split(new[] { "Environment.NewLine", "\r\n", "\n" }, StringSplitOptions.None); 
            
            #line default
            #line hidden
            
            #line 33 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 var last = lines.Last(); 
            
            #line default
            #line hidden
            
            #line 34 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 foreach(var line in lines ){ 
            
            #line default
            #line hidden
            this.Write("\t/// ");
            
            #line 35 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            
            #line 35 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 if(!line.Equals(last)){ 
            
            #line default
            #line hidden
            this.Write("<br/>\r\n");
            
            #line 36 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 37 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t/// </summary>\r\n");
            
            #line 40 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 41 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 if(thisProperty.Type is ISimpleType thisSimpleType) { 
            
            #line default
            #line hidden
            this.Write("\t[System.Xml.Serialization.XmlElementAttribute(\"");
            
            #line 42 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(thisSimpleType.PayloadTag));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\tpublic ");
            
            #line 43 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(thisSimpleType.Type.GetCSharpSyntax()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 43 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(thisProperty.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 44 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } else if(thisProperty.Type is IChoiceType thisChoiceType) { 
            
            #line default
            #line hidden
            
            #line 45 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 foreach(var choice in thisChoiceType.Variances) { 
            
            #line default
            #line hidden
            this.Write("\t[System.Xml.Serialization.XmlElementAttribute(\"");
            
            #line 46 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(choice.PayloadTag));
            
            #line default
            #line hidden
            this.Write("\", typeof(");
            
            #line 46 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(choice.ClassName));
            
            #line default
            #line hidden
            this.Write(")]\r\n");
            
            #line 47 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 48 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(thisChoiceType.BaseClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 48 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(thisProperty.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 49 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } else if(thisProperty.Type is IClassType thisClassType) { 
            
            #line default
            #line hidden
            this.Write("\t[System.Xml.Serialization.XmlElementAttribute(\"");
            
            #line 50 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(thisClassType.PayloadTag));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\tpublic ");
            
            #line 51 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(thisClassType.ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 51 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(thisProperty.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 52 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\tI will break your code...\t\r\n");
            
            #line 54 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 55 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 if(thisProperty != lastProperty) { 
            
            #line default
            #line hidden
            this.Write("\t\r\n");
            
            #line 57 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 58 "C:\Source\Zent.Iso20022\4.Source\PoCSolution\src\Zent.Iso20022.ClassGeneration\Templates\Xml\InheritorClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class InheritorClassTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
