//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05", IsNullable=false)]
public partial class Document {
    
    private CollateralAndExposureReportV05 collAndXpsrRptField;
    
    /// <remarks/>
    public CollateralAndExposureReportV05 CollAndXpsrRpt {
        get {
            return this.collAndXpsrRptField;
        }
        set {
            this.collAndXpsrRptField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class CollateralAndExposureReportV05 {
    
    private ReportParameters6 rptParamsField;
    
    private Pagination1 pgntnField;
    
    private Obligation11 oblgtnField;
    
    private Agreement4 agrmtField;
    
    private Collateral53[] collRptField;
    
    private SupplementaryData1[] splmtryDataField;
    
    /// <remarks/>
    public ReportParameters6 RptParams {
        get {
            return this.rptParamsField;
        }
        set {
            this.rptParamsField = value;
        }
    }
    
    /// <remarks/>
    public Pagination1 Pgntn {
        get {
            return this.pgntnField;
        }
        set {
            this.pgntnField = value;
        }
    }
    
    /// <remarks/>
    public Obligation11 Oblgtn {
        get {
            return this.oblgtnField;
        }
        set {
            this.oblgtnField = value;
        }
    }
    
    /// <remarks/>
    public Agreement4 Agrmt {
        get {
            return this.agrmtField;
        }
        set {
            this.agrmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CollRpt")]
    public Collateral53[] CollRpt {
        get {
            return this.collRptField;
        }
        set {
            this.collRptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
    public SupplementaryData1[] SplmtryData {
        get {
            return this.splmtryDataField;
        }
        set {
            this.splmtryDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class ReportParameters6 {
    
    private string rptIdField;
    
    private DateAndDateTime2Choice rptDtAndTmField;
    
    private EventFrequency6Code frqcyField;
    
    private string rptCcyField;
    
    private System.DateTime clctnDtField;
    
    private bool clctnDtFieldSpecified;
    
    /// <remarks/>
    public string RptId {
        get {
            return this.rptIdField;
        }
        set {
            this.rptIdField = value;
        }
    }
    
    /// <remarks/>
    public DateAndDateTime2Choice RptDtAndTm {
        get {
            return this.rptDtAndTmField;
        }
        set {
            this.rptDtAndTmField = value;
        }
    }
    
    /// <remarks/>
    public EventFrequency6Code Frqcy {
        get {
            return this.frqcyField;
        }
        set {
            this.frqcyField = value;
        }
    }
    
    /// <remarks/>
    public string RptCcy {
        get {
            return this.rptCcyField;
        }
        set {
            this.rptCcyField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ClctnDt {
        get {
            return this.clctnDtField;
        }
        set {
            this.clctnDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ClctnDtSpecified {
        get {
            return this.clctnDtFieldSpecified;
        }
        set {
            this.clctnDtFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class DateAndDateTime2Choice {
    
    private System.DateTime itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("DtTm", typeof(System.DateTime))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public System.DateTime Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    Dt,
    
    /// <remarks/>
    DtTm,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class SupplementaryData1 {
    
    private string plcAndNmField;
    
    private System.Xml.XmlElement envlpField;
    
    /// <remarks/>
    public string PlcAndNm {
        get {
            return this.plcAndNmField;
        }
        set {
            this.plcAndNmField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Envlp {
        get {
            return this.envlpField;
        }
        set {
            this.envlpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class DateCode9Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(DateType2Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum DateType2Code {
    
    /// <remarks/>
    OPEN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class GenericIdentification30 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class DateFormat14Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("DtCd", typeof(DateCode9Choice))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class OtherTypeOfCollateral3 {
    
    private string descField;
    
    private FinancialInstrumentQuantity33Choice qtyField;
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    public FinancialInstrumentQuantity33Choice Qty {
        get {
            return this.qtyField;
        }
        set {
            this.qtyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class FinancialInstrumentQuantity33Choice {
    
    private decimal itemField;
    
    private ItemChoiceType2 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AmtsdVal", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("DgtlTknUnit", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("FaceAmt", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(decimal))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public decimal Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType2 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05", IncludeInSchema=false)]
public enum ItemChoiceType2 {
    
    /// <remarks/>
    AmtsdVal,
    
    /// <remarks/>
    DgtlTknUnit,
    
    /// <remarks/>
    FaceAmt,
    
    /// <remarks/>
    Unit,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class OtherCollateral10 {
    
    private string asstNbField;
    
    private string lttrOfCdtIdField;
    
    private ActiveCurrencyAndAmount lttrOfCdtAmtField;
    
    private ActiveCurrencyAndAmount grntAmtField;
    
    private OtherTypeOfCollateral3 othrTpOfCollField;
    
    private CollateralOwnership3 collOwnrshField;
    
    private DateFormat14Choice isseDtField;
    
    private DateFormat14Choice xpryDtField;
    
    private bool ltdCvrgIndField;
    
    private bool ltdCvrgIndFieldSpecified;
    
    private PartyIdentification178Choice issrField;
    
    private FinancialInstrumentQuantity33Choice blckdQtyField;
    
    private System.DateTime valDtField;
    
    private bool valDtFieldSpecified;
    
    private decimal xchgRateField;
    
    private bool xchgRateFieldSpecified;
    
    private ActiveCurrencyAndAmount mktValField;
    
    private decimal hrcutField;
    
    private bool hrcutFieldSpecified;
    
    private ActiveCurrencyAndAmount collValField;
    
    private SafekeepingPlaceFormat29Choice sfkpgPlcField;
    
    private SecuritiesAccount19 sfkpgAcctField;
    
    private BlockChainAddressWallet3 blckChainAdrOrWlltField;
    
    /// <remarks/>
    public string AsstNb {
        get {
            return this.asstNbField;
        }
        set {
            this.asstNbField = value;
        }
    }
    
    /// <remarks/>
    public string LttrOfCdtId {
        get {
            return this.lttrOfCdtIdField;
        }
        set {
            this.lttrOfCdtIdField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount LttrOfCdtAmt {
        get {
            return this.lttrOfCdtAmtField;
        }
        set {
            this.lttrOfCdtAmtField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount GrntAmt {
        get {
            return this.grntAmtField;
        }
        set {
            this.grntAmtField = value;
        }
    }
    
    /// <remarks/>
    public OtherTypeOfCollateral3 OthrTpOfColl {
        get {
            return this.othrTpOfCollField;
        }
        set {
            this.othrTpOfCollField = value;
        }
    }
    
    /// <remarks/>
    public CollateralOwnership3 CollOwnrsh {
        get {
            return this.collOwnrshField;
        }
        set {
            this.collOwnrshField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat14Choice IsseDt {
        get {
            return this.isseDtField;
        }
        set {
            this.isseDtField = value;
        }
    }
    
    /// <remarks/>
    public DateFormat14Choice XpryDt {
        get {
            return this.xpryDtField;
        }
        set {
            this.xpryDtField = value;
        }
    }
    
    /// <remarks/>
    public bool LtdCvrgInd {
        get {
            return this.ltdCvrgIndField;
        }
        set {
            this.ltdCvrgIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LtdCvrgIndSpecified {
        get {
            return this.ltdCvrgIndFieldSpecified;
        }
        set {
            this.ltdCvrgIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification178Choice Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public FinancialInstrumentQuantity33Choice BlckdQty {
        get {
            return this.blckdQtyField;
        }
        set {
            this.blckdQtyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ValDt {
        get {
            return this.valDtField;
        }
        set {
            this.valDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValDtSpecified {
        get {
            return this.valDtFieldSpecified;
        }
        set {
            this.valDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal XchgRate {
        get {
            return this.xchgRateField;
        }
        set {
            this.xchgRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XchgRateSpecified {
        get {
            return this.xchgRateFieldSpecified;
        }
        set {
            this.xchgRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount MktVal {
        get {
            return this.mktValField;
        }
        set {
            this.mktValField = value;
        }
    }
    
    /// <remarks/>
    public decimal Hrcut {
        get {
            return this.hrcutField;
        }
        set {
            this.hrcutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HrcutSpecified {
        get {
            return this.hrcutFieldSpecified;
        }
        set {
            this.hrcutFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount CollVal {
        get {
            return this.collValField;
        }
        set {
            this.collValField = value;
        }
    }
    
    /// <remarks/>
    public SafekeepingPlaceFormat29Choice SfkpgPlc {
        get {
            return this.sfkpgPlcField;
        }
        set {
            this.sfkpgPlcField = value;
        }
    }
    
    /// <remarks/>
    public SecuritiesAccount19 SfkpgAcct {
        get {
            return this.sfkpgAcctField;
        }
        set {
            this.sfkpgAcctField = value;
        }
    }
    
    /// <remarks/>
    public BlockChainAddressWallet3 BlckChainAdrOrWllt {
        get {
            return this.blckChainAdrOrWlltField;
        }
        set {
            this.blckChainAdrOrWlltField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class ActiveCurrencyAndAmount {
    
    private string ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class CollateralOwnership3 {
    
    private bool prtryField;
    
    private PartyIdentification178Choice clntNmField;
    
    /// <remarks/>
    public bool Prtry {
        get {
            return this.prtryField;
        }
        set {
            this.prtryField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification178Choice ClntNm {
        get {
            return this.clntNmField;
        }
        set {
            this.clntNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class PartyIdentification178Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NmAndAdr", typeof(NameAndAddress6))]
    [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification36))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class NameAndAddress6 {
    
    private string nmField;
    
    private PostalAddress2 adrField;
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
    
    /// <remarks/>
    public PostalAddress2 Adr {
        get {
            return this.adrField;
        }
        set {
            this.adrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class PostalAddress2 {
    
    private string strtNmField;
    
    private string pstCdIdField;
    
    private string twnNmField;
    
    private string ctrySubDvsnField;
    
    private string ctryField;
    
    /// <remarks/>
    public string StrtNm {
        get {
            return this.strtNmField;
        }
        set {
            this.strtNmField = value;
        }
    }
    
    /// <remarks/>
    public string PstCdId {
        get {
            return this.pstCdIdField;
        }
        set {
            this.pstCdIdField = value;
        }
    }
    
    /// <remarks/>
    public string TwnNm {
        get {
            return this.twnNmField;
        }
        set {
            this.twnNmField = value;
        }
    }
    
    /// <remarks/>
    public string CtrySubDvsn {
        get {
            return this.ctrySubDvsnField;
        }
        set {
            this.ctrySubDvsnField = value;
        }
    }
    
    /// <remarks/>
    public string Ctry {
        get {
            return this.ctryField;
        }
        set {
            this.ctryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class GenericIdentification36 {
    
    private string idField;
    
    private string issrField;
    
    private string schmeNmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Issr {
        get {
            return this.issrField;
        }
        set {
            this.issrField = value;
        }
    }
    
    /// <remarks/>
    public string SchmeNm {
        get {
            return this.schmeNmField;
        }
        set {
            this.schmeNmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class SafekeepingPlaceFormat29Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ctry", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Id", typeof(SafekeepingPlaceTypeAndText8))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification78))]
    [System.Xml.Serialization.XmlElementAttribute("TpAndId", typeof(SafekeepingPlaceTypeAndIdentification1))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class SafekeepingPlaceTypeAndText8 {
    
    private SafekeepingPlace3Code sfkpgPlcTpField;
    
    private string idField;
    
    /// <remarks/>
    public SafekeepingPlace3Code SfkpgPlcTp {
        get {
            return this.sfkpgPlcTpField;
        }
        set {
            this.sfkpgPlcTpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum SafekeepingPlace3Code {
    
    /// <remarks/>
    SHHE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class GenericIdentification78 {
    
    private GenericIdentification30 tpField;
    
    private string idField;
    
    /// <remarks/>
    public GenericIdentification30 Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class SafekeepingPlaceTypeAndIdentification1 {
    
    private SafekeepingPlace1Code sfkpgPlcTpField;
    
    private string idField;
    
    /// <remarks/>
    public SafekeepingPlace1Code SfkpgPlcTp {
        get {
            return this.sfkpgPlcTpField;
        }
        set {
            this.sfkpgPlcTpField = value;
        }
    }
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum SafekeepingPlace1Code {
    
    /// <remarks/>
    CUST,
    
    /// <remarks/>
    ICSD,
    
    /// <remarks/>
    NCSD,
    
    /// <remarks/>
    SHHE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class SecuritiesAccount19 {
    
    private string idField;
    
    private GenericIdentification30 tpField;
    
    private string nmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification30 Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class BlockChainAddressWallet3 {
    
    private string idField;
    
    private GenericIdentification30 tpField;
    
    private string nmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public GenericIdentification30 Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class CashCollateral4 {
    
    private string asstNbField;
    
    private ActiveCurrencyAndAmount dpstAmtField;
    
    private DepositType1Code dpstTpField;
    
    private bool dpstTpFieldSpecified;
    
    private ActiveCurrencyAndAmount blckdAmtField;
    
    private System.DateTime mtrtyDtField;
    
    private bool mtrtyDtFieldSpecified;
    
    private System.DateTime valDtField;
    
    private bool valDtFieldSpecified;
    
    private decimal xchgRateField;
    
    private bool xchgRateFieldSpecified;
    
    private ActiveCurrencyAndAmount collValField;
    
    private decimal hrcutField;
    
    private bool hrcutFieldSpecified;
    
    /// <remarks/>
    public string AsstNb {
        get {
            return this.asstNbField;
        }
        set {
            this.asstNbField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount DpstAmt {
        get {
            return this.dpstAmtField;
        }
        set {
            this.dpstAmtField = value;
        }
    }
    
    /// <remarks/>
    public DepositType1Code DpstTp {
        get {
            return this.dpstTpField;
        }
        set {
            this.dpstTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DpstTpSpecified {
        get {
            return this.dpstTpFieldSpecified;
        }
        set {
            this.dpstTpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount BlckdAmt {
        get {
            return this.blckdAmtField;
        }
        set {
            this.blckdAmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime MtrtyDt {
        get {
            return this.mtrtyDtField;
        }
        set {
            this.mtrtyDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MtrtyDtSpecified {
        get {
            return this.mtrtyDtFieldSpecified;
        }
        set {
            this.mtrtyDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ValDt {
        get {
            return this.valDtField;
        }
        set {
            this.valDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValDtSpecified {
        get {
            return this.valDtFieldSpecified;
        }
        set {
            this.valDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal XchgRate {
        get {
            return this.xchgRateField;
        }
        set {
            this.xchgRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XchgRateSpecified {
        get {
            return this.xchgRateFieldSpecified;
        }
        set {
            this.xchgRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount CollVal {
        get {
            return this.collValField;
        }
        set {
            this.collValField = value;
        }
    }
    
    /// <remarks/>
    public decimal Hrcut {
        get {
            return this.hrcutField;
        }
        set {
            this.hrcutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HrcutSpecified {
        get {
            return this.hrcutFieldSpecified;
        }
        set {
            this.hrcutFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum DepositType1Code {
    
    /// <remarks/>
    FITE,
    
    /// <remarks/>
    CALL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class ActiveOrHistoricCurrencyAnd13DecimalAmount {
    
    private string ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class PriceRateOrAmount3Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Amt", typeof(ActiveOrHistoricCurrencyAnd13DecimalAmount))]
    [System.Xml.Serialization.XmlElementAttribute("Rate", typeof(decimal))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class YieldedOrValueType1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ValTp", typeof(PriceValueType1Code))]
    [System.Xml.Serialization.XmlElementAttribute("Yldd", typeof(bool))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum PriceValueType1Code {
    
    /// <remarks/>
    DISC,
    
    /// <remarks/>
    PREM,
    
    /// <remarks/>
    PARV,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class Price7 {
    
    private YieldedOrValueType1Choice tpField;
    
    private PriceRateOrAmount3Choice valField;
    
    /// <remarks/>
    public YieldedOrValueType1Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public PriceRateOrAmount3Choice Val {
        get {
            return this.valField;
        }
        set {
            this.valField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class IdentificationSource3Choice {
    
    private string itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    Cd,
    
    /// <remarks/>
    Prtry,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class OtherIdentification1 {
    
    private string idField;
    
    private string sfxField;
    
    private IdentificationSource3Choice tpField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Sfx {
        get {
            return this.sfxField;
        }
        set {
            this.sfxField = value;
        }
    }
    
    /// <remarks/>
    public IdentificationSource3Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class SecurityIdentification19 {
    
    private string iSINField;
    
    private OtherIdentification1[] othrIdField;
    
    private string descField;
    
    /// <remarks/>
    public string ISIN {
        get {
            return this.iSINField;
        }
        set {
            this.iSINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OthrId")]
    public OtherIdentification1[] OthrId {
        get {
            return this.othrIdField;
        }
        set {
            this.othrIdField = value;
        }
    }
    
    /// <remarks/>
    public string Desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class SecuritiesCollateral13 {
    
    private string asstNbField;
    
    private SecurityIdentification19 sctyIdField;
    
    private DateAndDateTime2Choice mtrtyDtField;
    
    private CollateralOwnership3 collOwnrshField;
    
    private bool ltdCvrgIndField;
    
    private bool ltdCvrgIndFieldSpecified;
    
    private FinancialInstrumentQuantity33Choice qtyField;
    
    private FinancialInstrumentQuantity33Choice blckdQtyField;
    
    private Price7 pricField;
    
    private ActiveCurrencyAndAmount mktValField;
    
    private decimal hrcutField;
    
    private bool hrcutFieldSpecified;
    
    private ActiveCurrencyAndAmount collValField;
    
    private System.DateTime valDtField;
    
    private bool valDtFieldSpecified;
    
    private SecuritiesAccount19 sfkpgAcctField;
    
    private BlockChainAddressWallet3 blckChainAdrOrWlltField;
    
    private SafekeepingPlaceFormat29Choice sfkpgPlcField;
    
    /// <remarks/>
    public string AsstNb {
        get {
            return this.asstNbField;
        }
        set {
            this.asstNbField = value;
        }
    }
    
    /// <remarks/>
    public SecurityIdentification19 SctyId {
        get {
            return this.sctyIdField;
        }
        set {
            this.sctyIdField = value;
        }
    }
    
    /// <remarks/>
    public DateAndDateTime2Choice MtrtyDt {
        get {
            return this.mtrtyDtField;
        }
        set {
            this.mtrtyDtField = value;
        }
    }
    
    /// <remarks/>
    public CollateralOwnership3 CollOwnrsh {
        get {
            return this.collOwnrshField;
        }
        set {
            this.collOwnrshField = value;
        }
    }
    
    /// <remarks/>
    public bool LtdCvrgInd {
        get {
            return this.ltdCvrgIndField;
        }
        set {
            this.ltdCvrgIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LtdCvrgIndSpecified {
        get {
            return this.ltdCvrgIndFieldSpecified;
        }
        set {
            this.ltdCvrgIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public FinancialInstrumentQuantity33Choice Qty {
        get {
            return this.qtyField;
        }
        set {
            this.qtyField = value;
        }
    }
    
    /// <remarks/>
    public FinancialInstrumentQuantity33Choice BlckdQty {
        get {
            return this.blckdQtyField;
        }
        set {
            this.blckdQtyField = value;
        }
    }
    
    /// <remarks/>
    public Price7 Pric {
        get {
            return this.pricField;
        }
        set {
            this.pricField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount MktVal {
        get {
            return this.mktValField;
        }
        set {
            this.mktValField = value;
        }
    }
    
    /// <remarks/>
    public decimal Hrcut {
        get {
            return this.hrcutField;
        }
        set {
            this.hrcutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HrcutSpecified {
        get {
            return this.hrcutFieldSpecified;
        }
        set {
            this.hrcutFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount CollVal {
        get {
            return this.collValField;
        }
        set {
            this.collValField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ValDt {
        get {
            return this.valDtField;
        }
        set {
            this.valDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValDtSpecified {
        get {
            return this.valDtFieldSpecified;
        }
        set {
            this.valDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public SecuritiesAccount19 SfkpgAcct {
        get {
            return this.sfkpgAcctField;
        }
        set {
            this.sfkpgAcctField = value;
        }
    }
    
    /// <remarks/>
    public BlockChainAddressWallet3 BlckChainAdrOrWllt {
        get {
            return this.blckChainAdrOrWlltField;
        }
        set {
            this.blckChainAdrOrWlltField = value;
        }
    }
    
    /// <remarks/>
    public SafekeepingPlaceFormat29Choice SfkpgPlc {
        get {
            return this.sfkpgPlcField;
        }
        set {
            this.sfkpgPlcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class CollateralAmount1 {
    
    private ActiveCurrencyAndAmount collAmtField;
    
    private ActiveCurrencyAndAmount rptdCcyAndAmtField;
    
    private ActiveCurrencyAndAmount mktValAmtField;
    
    private ActiveCurrencyAndAmount acrdIntrstAmtField;
    
    private ActiveCurrencyAndAmount feesAndComssnsField;
    
    /// <remarks/>
    public ActiveCurrencyAndAmount CollAmt {
        get {
            return this.collAmtField;
        }
        set {
            this.collAmtField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount RptdCcyAndAmt {
        get {
            return this.rptdCcyAndAmtField;
        }
        set {
            this.rptdCcyAndAmtField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount MktValAmt {
        get {
            return this.mktValAmtField;
        }
        set {
            this.mktValAmtField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount AcrdIntrstAmt {
        get {
            return this.acrdIntrstAmtField;
        }
        set {
            this.acrdIntrstAmtField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount FeesAndComssns {
        get {
            return this.feesAndComssnsField;
        }
        set {
            this.feesAndComssnsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class CollateralValuation13 {
    
    private string collIdField;
    
    private CollateralType8Code collTpField;
    
    private CollateralDirection1Code collDrctnField;
    
    private bool collDrctnFieldSpecified;
    
    private SettlementStatus3Code sttlmStsField;
    
    private CollateralAppliedExcess1Code apldXcssIndField;
    
    private bool apldXcssIndFieldSpecified;
    
    private decimal nbOfDaysAcrdField;
    
    private bool nbOfDaysAcrdFieldSpecified;
    
    private CollateralAmount1 valtnAmtsField;
    
    private InterestComputationMethod2Code dayCntBsisField;
    
    private bool dayCntBsisFieldSpecified;
    
    private decimal xchgRateField;
    
    private bool xchgRateFieldSpecified;
    
    private decimal ccyHrcutField;
    
    private bool ccyHrcutFieldSpecified;
    
    private decimal adjstdRateField;
    
    private bool adjstdRateFieldSpecified;
    
    private SecuritiesCollateral13 sctiesCollField;
    
    private CashCollateral4 cshCollField;
    
    private OtherCollateral10 othrCollField;
    
    /// <remarks/>
    public string CollId {
        get {
            return this.collIdField;
        }
        set {
            this.collIdField = value;
        }
    }
    
    /// <remarks/>
    public CollateralType8Code CollTp {
        get {
            return this.collTpField;
        }
        set {
            this.collTpField = value;
        }
    }
    
    /// <remarks/>
    public CollateralDirection1Code CollDrctn {
        get {
            return this.collDrctnField;
        }
        set {
            this.collDrctnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CollDrctnSpecified {
        get {
            return this.collDrctnFieldSpecified;
        }
        set {
            this.collDrctnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public SettlementStatus3Code SttlmSts {
        get {
            return this.sttlmStsField;
        }
        set {
            this.sttlmStsField = value;
        }
    }
    
    /// <remarks/>
    public CollateralAppliedExcess1Code ApldXcssInd {
        get {
            return this.apldXcssIndField;
        }
        set {
            this.apldXcssIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ApldXcssIndSpecified {
        get {
            return this.apldXcssIndFieldSpecified;
        }
        set {
            this.apldXcssIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal NbOfDaysAcrd {
        get {
            return this.nbOfDaysAcrdField;
        }
        set {
            this.nbOfDaysAcrdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NbOfDaysAcrdSpecified {
        get {
            return this.nbOfDaysAcrdFieldSpecified;
        }
        set {
            this.nbOfDaysAcrdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public CollateralAmount1 ValtnAmts {
        get {
            return this.valtnAmtsField;
        }
        set {
            this.valtnAmtsField = value;
        }
    }
    
    /// <remarks/>
    public InterestComputationMethod2Code DayCntBsis {
        get {
            return this.dayCntBsisField;
        }
        set {
            this.dayCntBsisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DayCntBsisSpecified {
        get {
            return this.dayCntBsisFieldSpecified;
        }
        set {
            this.dayCntBsisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal XchgRate {
        get {
            return this.xchgRateField;
        }
        set {
            this.xchgRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XchgRateSpecified {
        get {
            return this.xchgRateFieldSpecified;
        }
        set {
            this.xchgRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal CcyHrcut {
        get {
            return this.ccyHrcutField;
        }
        set {
            this.ccyHrcutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CcyHrcutSpecified {
        get {
            return this.ccyHrcutFieldSpecified;
        }
        set {
            this.ccyHrcutFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal AdjstdRate {
        get {
            return this.adjstdRateField;
        }
        set {
            this.adjstdRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AdjstdRateSpecified {
        get {
            return this.adjstdRateFieldSpecified;
        }
        set {
            this.adjstdRateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public SecuritiesCollateral13 SctiesColl {
        get {
            return this.sctiesCollField;
        }
        set {
            this.sctiesCollField = value;
        }
    }
    
    /// <remarks/>
    public CashCollateral4 CshColl {
        get {
            return this.cshCollField;
        }
        set {
            this.cshCollField = value;
        }
    }
    
    /// <remarks/>
    public OtherCollateral10 OthrColl {
        get {
            return this.othrCollField;
        }
        set {
            this.othrCollField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum CollateralType8Code {
    
    /// <remarks/>
    COMO,
    
    /// <remarks/>
    CCCL,
    
    /// <remarks/>
    CEMC,
    
    /// <remarks/>
    CXCC,
    
    /// <remarks/>
    CFTD,
    
    /// <remarks/>
    CFTI,
    
    /// <remarks/>
    CTRC,
    
    /// <remarks/>
    CASH,
    
    /// <remarks/>
    LCRE,
    
    /// <remarks/>
    OTHR,
    
    /// <remarks/>
    SECU,
    
    /// <remarks/>
    CTCO,
    
    /// <remarks/>
    CCVR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum CollateralDirection1Code {
    
    /// <remarks/>
    CDPA,
    
    /// <remarks/>
    CDPB,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum SettlementStatus3Code {
    
    /// <remarks/>
    ASTL,
    
    /// <remarks/>
    AAUT,
    
    /// <remarks/>
    ACCF,
    
    /// <remarks/>
    ARCF,
    
    /// <remarks/>
    MTCH,
    
    /// <remarks/>
    PSTL,
    
    /// <remarks/>
    RJCT,
    
    /// <remarks/>
    STLD,
    
    /// <remarks/>
    STCR,
    
    /// <remarks/>
    SPLT,
    
    /// <remarks/>
    NMAT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum CollateralAppliedExcess1Code {
    
    /// <remarks/>
    APLD,
    
    /// <remarks/>
    EXCS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum InterestComputationMethod2Code {
    
    /// <remarks/>
    A001,
    
    /// <remarks/>
    A002,
    
    /// <remarks/>
    A003,
    
    /// <remarks/>
    A004,
    
    /// <remarks/>
    A005,
    
    /// <remarks/>
    A006,
    
    /// <remarks/>
    A007,
    
    /// <remarks/>
    A008,
    
    /// <remarks/>
    A009,
    
    /// <remarks/>
    A010,
    
    /// <remarks/>
    A011,
    
    /// <remarks/>
    A012,
    
    /// <remarks/>
    A013,
    
    /// <remarks/>
    A014,
    
    /// <remarks/>
    NARR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class ReturnExcessCash1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(ReturnExcessCash1Code))]
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum ReturnExcessCash1Code {
    
    /// <remarks/>
    RTND,
    
    /// <remarks/>
    RTDN,
    
    /// <remarks/>
    SSPD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class ReturnExcessCash1 {
    
    private ReturnExcessCash1Choice rtrXcssCshTpField;
    
    private string cshCollCcyField;
    
    /// <remarks/>
    public ReturnExcessCash1Choice RtrXcssCshTp {
        get {
            return this.rtrXcssCshTpField;
        }
        set {
            this.rtrXcssCshTpField = value;
        }
    }
    
    /// <remarks/>
    public string CshCollCcy {
        get {
            return this.cshCollCcyField;
        }
        set {
            this.cshCollCcyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class SummaryAmounts2 {
    
    private ActiveCurrencyAndAmount thrshldAmtField;
    
    private ThresholdType1Code thrshldTpField;
    
    private bool thrshldTpFieldSpecified;
    
    private ActiveCurrencyAndAmount preHrcutCollValField;
    
    private ActiveCurrencyAndAmount adjstdXpsrField;
    
    private ActiveCurrencyAndAmount collReqrdField;
    
    private ReturnExcessCash1[] rtrXcssCshAndCollCcyField;
    
    private ActiveCurrencyAndAmount minTrfAmtField;
    
    private ActiveCurrencyAndAmount rndgAmtField;
    
    private ActiveCurrencyAndAmount prvsXpsrValField;
    
    private ActiveCurrencyAndAmount prvsCollValField;
    
    private ActiveCurrencyAndAmount ttlPdgIncmgCollField;
    
    private ActiveCurrencyAndAmount ttlPdgOutgngCollField;
    
    private ActiveCurrencyAndAmount ttlAcrdIntrstAmtField;
    
    private ActiveCurrencyAndAmount ttlFeesField;
    
    /// <remarks/>
    public ActiveCurrencyAndAmount ThrshldAmt {
        get {
            return this.thrshldAmtField;
        }
        set {
            this.thrshldAmtField = value;
        }
    }
    
    /// <remarks/>
    public ThresholdType1Code ThrshldTp {
        get {
            return this.thrshldTpField;
        }
        set {
            this.thrshldTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ThrshldTpSpecified {
        get {
            return this.thrshldTpFieldSpecified;
        }
        set {
            this.thrshldTpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount PreHrcutCollVal {
        get {
            return this.preHrcutCollValField;
        }
        set {
            this.preHrcutCollValField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount AdjstdXpsr {
        get {
            return this.adjstdXpsrField;
        }
        set {
            this.adjstdXpsrField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount CollReqrd {
        get {
            return this.collReqrdField;
        }
        set {
            this.collReqrdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RtrXcssCshAndCollCcy")]
    public ReturnExcessCash1[] RtrXcssCshAndCollCcy {
        get {
            return this.rtrXcssCshAndCollCcyField;
        }
        set {
            this.rtrXcssCshAndCollCcyField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount MinTrfAmt {
        get {
            return this.minTrfAmtField;
        }
        set {
            this.minTrfAmtField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount RndgAmt {
        get {
            return this.rndgAmtField;
        }
        set {
            this.rndgAmtField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount PrvsXpsrVal {
        get {
            return this.prvsXpsrValField;
        }
        set {
            this.prvsXpsrValField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount PrvsCollVal {
        get {
            return this.prvsCollValField;
        }
        set {
            this.prvsCollValField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount TtlPdgIncmgColl {
        get {
            return this.ttlPdgIncmgCollField;
        }
        set {
            this.ttlPdgIncmgCollField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount TtlPdgOutgngColl {
        get {
            return this.ttlPdgOutgngCollField;
        }
        set {
            this.ttlPdgOutgngCollField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount TtlAcrdIntrstAmt {
        get {
            return this.ttlAcrdIntrstAmtField;
        }
        set {
            this.ttlAcrdIntrstAmtField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount TtlFees {
        get {
            return this.ttlFeesField;
        }
        set {
            this.ttlFeesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum ThresholdType1Code {
    
    /// <remarks/>
    SECU,
    
    /// <remarks/>
    UNSE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class Summary3 {
    
    private ActiveCurrencyAndAmount xpsdAmtPtyAField;
    
    private ActiveCurrencyAndAmount xpsdAmtPtyBField;
    
    private ExposureType13Code xpsrTpField;
    
    private ActiveCurrencyAndAmount ttlValOfCollField;
    
    private ActiveCurrencyAndAmount netXcssDfcitField;
    
    private ShortLong1Code netXcssDfcitIndField;
    
    private bool netXcssDfcitIndFieldSpecified;
    
    private System.DateTime valtnDtTmField;
    
    private System.DateTime reqdSttlmDtField;
    
    private bool reqdSttlmDtFieldSpecified;
    
    private SummaryAmounts2 summryDtlsField;
    
    /// <remarks/>
    public ActiveCurrencyAndAmount XpsdAmtPtyA {
        get {
            return this.xpsdAmtPtyAField;
        }
        set {
            this.xpsdAmtPtyAField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount XpsdAmtPtyB {
        get {
            return this.xpsdAmtPtyBField;
        }
        set {
            this.xpsdAmtPtyBField = value;
        }
    }
    
    /// <remarks/>
    public ExposureType13Code XpsrTp {
        get {
            return this.xpsrTpField;
        }
        set {
            this.xpsrTpField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount TtlValOfColl {
        get {
            return this.ttlValOfCollField;
        }
        set {
            this.ttlValOfCollField = value;
        }
    }
    
    /// <remarks/>
    public ActiveCurrencyAndAmount NetXcssDfcit {
        get {
            return this.netXcssDfcitField;
        }
        set {
            this.netXcssDfcitField = value;
        }
    }
    
    /// <remarks/>
    public ShortLong1Code NetXcssDfcitInd {
        get {
            return this.netXcssDfcitIndField;
        }
        set {
            this.netXcssDfcitIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NetXcssDfcitIndSpecified {
        get {
            return this.netXcssDfcitIndFieldSpecified;
        }
        set {
            this.netXcssDfcitIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ValtnDtTm {
        get {
            return this.valtnDtTmField;
        }
        set {
            this.valtnDtTmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ReqdSttlmDt {
        get {
            return this.reqdSttlmDtField;
        }
        set {
            this.reqdSttlmDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReqdSttlmDtSpecified {
        get {
            return this.reqdSttlmDtFieldSpecified;
        }
        set {
            this.reqdSttlmDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public SummaryAmounts2 SummryDtls {
        get {
            return this.summryDtlsField;
        }
        set {
            this.summryDtlsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum ExposureType13Code {
    
    /// <remarks/>
    CCIR,
    
    /// <remarks/>
    CRPR,
    
    /// <remarks/>
    EQUI,
    
    /// <remarks/>
    EQPT,
    
    /// <remarks/>
    EQUS,
    
    /// <remarks/>
    EXTD,
    
    /// <remarks/>
    EXPT,
    
    /// <remarks/>
    FIXI,
    
    /// <remarks/>
    FORX,
    
    /// <remarks/>
    FORW,
    
    /// <remarks/>
    FUTR,
    
    /// <remarks/>
    OPTN,
    
    /// <remarks/>
    LIQU,
    
    /// <remarks/>
    MGLD,
    
    /// <remarks/>
    OTCD,
    
    /// <remarks/>
    REPO,
    
    /// <remarks/>
    RVPO,
    
    /// <remarks/>
    SLOA,
    
    /// <remarks/>
    SBSC,
    
    /// <remarks/>
    SCRP,
    
    /// <remarks/>
    SLEB,
    
    /// <remarks/>
    SHSL,
    
    /// <remarks/>
    SCIR,
    
    /// <remarks/>
    SCIE,
    
    /// <remarks/>
    ESCL,
    
    /// <remarks/>
    SWPT,
    
    /// <remarks/>
    TBAS,
    
    /// <remarks/>
    ECRT,
    
    /// <remarks/>
    ECFR,
    
    /// <remarks/>
    EMLO,
    
    /// <remarks/>
    EMLI,
    
    /// <remarks/>
    EOIM,
    
    /// <remarks/>
    EOMI,
    
    /// <remarks/>
    TRBD,
    
    /// <remarks/>
    BFWD,
    
    /// <remarks/>
    PAYM,
    
    /// <remarks/>
    CCPC,
    
    /// <remarks/>
    COMM,
    
    /// <remarks/>
    CRDS,
    
    /// <remarks/>
    CRTL,
    
    /// <remarks/>
    CRSP,
    
    /// <remarks/>
    EOMO,
    
    /// <remarks/>
    CBCO,
    
    /// <remarks/>
    TRCP,
    
    /// <remarks/>
    UDMS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum ShortLong1Code {
    
    /// <remarks/>
    SHOR,
    
    /// <remarks/>
    LONG,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class Collateral53 {
    
    private CollateralAccount3 acctIdField;
    
    private BlockChainAddressWallet5 blckChainAdrOrWlltField;
    
    private Summary3 rptSummryField;
    
    private CollateralValuation13[] collValtnField;
    
    /// <remarks/>
    public CollateralAccount3 AcctId {
        get {
            return this.acctIdField;
        }
        set {
            this.acctIdField = value;
        }
    }
    
    /// <remarks/>
    public BlockChainAddressWallet5 BlckChainAdrOrWllt {
        get {
            return this.blckChainAdrOrWlltField;
        }
        set {
            this.blckChainAdrOrWlltField = value;
        }
    }
    
    /// <remarks/>
    public Summary3 RptSummry {
        get {
            return this.rptSummryField;
        }
        set {
            this.rptSummryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CollValtn")]
    public CollateralValuation13[] CollValtn {
        get {
            return this.collValtnField;
        }
        set {
            this.collValtnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class CollateralAccount3 {
    
    private string idField;
    
    private CollateralAccountIdentificationType3Choice tpField;
    
    private string nmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public CollateralAccountIdentificationType3Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class CollateralAccountIdentificationType3Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification36))]
    [System.Xml.Serialization.XmlElementAttribute("Tp", typeof(CollateralAccountType1Code))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum CollateralAccountType1Code {
    
    /// <remarks/>
    HOUS,
    
    /// <remarks/>
    CLIE,
    
    /// <remarks/>
    LIPR,
    
    /// <remarks/>
    MGIN,
    
    /// <remarks/>
    DFLT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class BlockChainAddressWallet5 {
    
    private string idField;
    
    private CollateralAccountIdentificationType3Choice tpField;
    
    private string nmField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public CollateralAccountIdentificationType3Choice Tp {
        get {
            return this.tpField;
        }
        set {
            this.tpField = value;
        }
    }
    
    /// <remarks/>
    public string Nm {
        get {
            return this.nmField;
        }
        set {
            this.nmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class AgreementFramework1Choice {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AgrmtFrmwk", typeof(AgreementFramework1Code))]
    [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification30))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum AgreementFramework1Code {
    
    /// <remarks/>
    FBAA,
    
    /// <remarks/>
    BBAA,
    
    /// <remarks/>
    DERV,
    
    /// <remarks/>
    ISDA,
    
    /// <remarks/>
    NONR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class Agreement4 {
    
    private string agrmtDtlsField;
    
    private string agrmtIdField;
    
    private System.DateTime agrmtDtField;
    
    private string baseCcyField;
    
    private AgreementFramework1Choice agrmtFrmwkField;
    
    /// <remarks/>
    public string AgrmtDtls {
        get {
            return this.agrmtDtlsField;
        }
        set {
            this.agrmtDtlsField = value;
        }
    }
    
    /// <remarks/>
    public string AgrmtId {
        get {
            return this.agrmtIdField;
        }
        set {
            this.agrmtIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime AgrmtDt {
        get {
            return this.agrmtDtField;
        }
        set {
            this.agrmtDtField = value;
        }
    }
    
    /// <remarks/>
    public string BaseCcy {
        get {
            return this.baseCcyField;
        }
        set {
            this.baseCcyField = value;
        }
    }
    
    /// <remarks/>
    public AgreementFramework1Choice AgrmtFrmwk {
        get {
            return this.agrmtFrmwkField;
        }
        set {
            this.agrmtFrmwkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class PartyIdentification242 {
    
    private PartyIdentification178Choice idField;
    
    private CCPMemberType1Code cCPMmbTpField;
    
    private bool cCPMmbTpFieldSpecified;
    
    /// <remarks/>
    public PartyIdentification178Choice Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public CCPMemberType1Code CCPMmbTp {
        get {
            return this.cCPMmbTpField;
        }
        set {
            this.cCPMmbTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CCPMmbTpSpecified {
        get {
            return this.cCPMmbTpFieldSpecified;
        }
        set {
            this.cCPMmbTpFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum CCPMemberType1Code {
    
    /// <remarks/>
    ACMB,
    
    /// <remarks/>
    CCPX,
    
    /// <remarks/>
    DCMB,
    
    /// <remarks/>
    FCMC,
    
    /// <remarks/>
    GCMB,
    
    /// <remarks/>
    SCMB,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class Obligation11 {
    
    private PartyIdentification242 ptyAField;
    
    private PartyIdentification178Choice svcgPtyAField;
    
    private PartyIdentification242 ptyBField;
    
    private PartyIdentification178Choice svcgPtyBField;
    
    private CollateralAccount3 collAcctIdField;
    
    private BlockChainAddressWallet5 blckChainAdrOrWlltField;
    
    private ExposureType11Code xpsrTpField;
    
    private bool xpsrTpFieldSpecified;
    
    private DateAndDateTime2Choice valtnDtField;
    
    /// <remarks/>
    public PartyIdentification242 PtyA {
        get {
            return this.ptyAField;
        }
        set {
            this.ptyAField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification178Choice SvcgPtyA {
        get {
            return this.svcgPtyAField;
        }
        set {
            this.svcgPtyAField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification242 PtyB {
        get {
            return this.ptyBField;
        }
        set {
            this.ptyBField = value;
        }
    }
    
    /// <remarks/>
    public PartyIdentification178Choice SvcgPtyB {
        get {
            return this.svcgPtyBField;
        }
        set {
            this.svcgPtyBField = value;
        }
    }
    
    /// <remarks/>
    public CollateralAccount3 CollAcctId {
        get {
            return this.collAcctIdField;
        }
        set {
            this.collAcctIdField = value;
        }
    }
    
    /// <remarks/>
    public BlockChainAddressWallet5 BlckChainAdrOrWllt {
        get {
            return this.blckChainAdrOrWlltField;
        }
        set {
            this.blckChainAdrOrWlltField = value;
        }
    }
    
    /// <remarks/>
    public ExposureType11Code XpsrTp {
        get {
            return this.xpsrTpField;
        }
        set {
            this.xpsrTpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool XpsrTpSpecified {
        get {
            return this.xpsrTpFieldSpecified;
        }
        set {
            this.xpsrTpFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public DateAndDateTime2Choice ValtnDt {
        get {
            return this.valtnDtField;
        }
        set {
            this.valtnDtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum ExposureType11Code {
    
    /// <remarks/>
    BFWD,
    
    /// <remarks/>
    PAYM,
    
    /// <remarks/>
    CBCO,
    
    /// <remarks/>
    COMM,
    
    /// <remarks/>
    CRDS,
    
    /// <remarks/>
    CRTL,
    
    /// <remarks/>
    CRSP,
    
    /// <remarks/>
    CCIR,
    
    /// <remarks/>
    CRPR,
    
    /// <remarks/>
    EQPT,
    
    /// <remarks/>
    EQUS,
    
    /// <remarks/>
    EXTD,
    
    /// <remarks/>
    EXPT,
    
    /// <remarks/>
    FIXI,
    
    /// <remarks/>
    FORX,
    
    /// <remarks/>
    FORW,
    
    /// <remarks/>
    FUTR,
    
    /// <remarks/>
    OPTN,
    
    /// <remarks/>
    LIQU,
    
    /// <remarks/>
    OTCD,
    
    /// <remarks/>
    RVPO,
    
    /// <remarks/>
    SLOA,
    
    /// <remarks/>
    SBSC,
    
    /// <remarks/>
    SCRP,
    
    /// <remarks/>
    SLEB,
    
    /// <remarks/>
    SCIR,
    
    /// <remarks/>
    SCIE,
    
    /// <remarks/>
    SWPT,
    
    /// <remarks/>
    TBAS,
    
    /// <remarks/>
    TRCP,
    
    /// <remarks/>
    UDMS,
    
    /// <remarks/>
    CCPC,
    
    /// <remarks/>
    EQUI,
    
    /// <remarks/>
    TRBD,
    
    /// <remarks/>
    REPO,
    
    /// <remarks/>
    SHSL,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public partial class Pagination1 {
    
    private string pgNbField;
    
    private bool lastPgIndField;
    
    /// <remarks/>
    public string PgNb {
        get {
            return this.pgNbField;
        }
        set {
            this.pgNbField = value;
        }
    }
    
    /// <remarks/>
    public bool LastPgInd {
        get {
            return this.lastPgIndField;
        }
        set {
            this.lastPgIndField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.016.001.05")]
public enum EventFrequency6Code {
    
    /// <remarks/>
    DAIL,
    
    /// <remarks/>
    INDA,
    
    /// <remarks/>
    ONDE,
}
